export { Switch, type SwitchProps } from './switch'
export { SwitchControl, type SwitchControlProps } from './switch-control'
export { SwitchInput, type SwitchInputProps } from './switch-input'
export { SwitchLabel, type SwitchLabelProps } from './switch-label'
export { SwitchThumb, type SwitchThumbProps } from './switch-thumb'
export { switchAnatomy } from './switch.anatomy'
