coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 2%
    patch:
      default:
        informational: true

flag_management:
  individual_flags:
    - name: react
      paths:
        - packages/react/
    - name: solid
      paths:
        - packages/solid/
    - name: vue
      paths:
        - packages/vue/
