import { code } from './code'
import { datePicker } from './date-picker'
import { markdown } from './markdown'

export const recipes = {
  // accordion,
  // avatar,
  // badge,
  // button,
  // carousel,
  // checkbox,
  code,
  // colorPicker,
  datePicker,
  // dialog,
  // divider,
  // drawer,
  // hoverCard,
  // input,
  // link,
  markdown,
  // menu,
  // numberInput,
  // pagination,
  // pinInput,
  // popover,
  // radio,
  // radioGroup,
  // ratingGroup,
  // segmentGroup,
  // select,
  // slider,
  // splitter,
  // switchRecipe,
  // tabs,
  // tagsInput,
  // toast,
  // tooltip,
}
