export { Tag, type TagProps } from './tag'
export { TagDeleteTrigger, type TagDeleteTriggerProps } from './tag-delete-trigger'
export { TagInput, type TagInputProps } from './tag-input'
export { TagsInput, type TagsInputProps } from './tags-input'
export { TagsInputClearTrigger, type TagsInputClearTriggerProps } from './tags-input-clear-trigger'
export { TagsInputControl, type TagsInputControlProps } from './tags-input-control'
export { TagsInputField, type TagsInputFieldProps } from './tags-input-field'
export { TagsInputLabel, type TagsInputLabelProps } from './tags-input-label'
export { tagsInputAnatomy } from './tags-input.anatomy'
