export type {
  Api as SplitterApi,
  ElementIds as SplitterElementIds,
  ExpandCollapseDetails as SplitterExpandCollapseDetails,
  HitAreaMargins as SplitterHitAreaMargins,
  Machine as SplitterMachine,
  PanelData as SplitterPanelData,
  PanelId as SplitterPanelId,
  PanelItem as SplitterPanelItem,
  PanelProps as SplitterPanelProps,
  Props as SplitterMachineProps,
  ResizeDetails as SplitterResizeDetails,
  ResizeEndDetails as SplitterResizeEndDetails,
  ResizeEvent as SplitterResizeEvent,
  ResizeTriggerId as SplitterResizeTriggerId,
  ResizeTriggerItem as SplitterResizeTriggerItem,
  ResizeTriggerProps as SplitterResizeTriggerProps,
  ResizeTriggerState as SplitterResizeTriggerState,
  Service as SplitterService,
  SplitterRegistry,
  SplitterRegistryOptions,
} from '@zag-js/splitter'
