export type { ActiveChangeDetails as TocActiveChangeDetails, TocItem as TocItemData } from '@zag-js/toc'
export { TocContent, type TocContentBaseProps, type TocContentProps } from './toc-content.tsx'
export { TocContext, type TocContextProps } from './toc-context.tsx'
export { TocIndicator, type TocIndicatorBaseProps, type TocIndicatorProps } from './toc-indicator.tsx'
export { TocItem, type TocItemBaseProps, type TocItemProps } from './toc-item.tsx'
export { TocLink, type TocLinkBaseProps, type TocLinkProps } from './toc-link.tsx'
export { TocList, type TocListBaseProps, type TocListProps } from './toc-list.tsx'
export { TocNav, type TocNavBaseProps, type TocNavProps } from './toc-nav.tsx'
export { TocRoot, type TocRootBaseProps, type TocRootProps } from './toc-root.tsx'
export { TocRootProvider, type TocRootProviderBaseProps, type TocRootProviderProps } from './toc-root-provider.tsx'
export { TocTitle, type TocTitleBaseProps, type TocTitleProps } from './toc-title.tsx'
export { tocAnatomy } from './toc.anatomy.ts'
export { useToc, type UseTocProps, type UseTocReturn } from './use-toc.ts'
export { useTocContext, type UseTocContext } from './use-toc-context.ts'

export * as Toc from './toc.ts'
