export { Avatar, type AvatarProps } from './avatar'
export { useAvatarContext } from './avatar-context'
export { AvatarFallback, type AvatarFallbackProps } from './avatar-fallback'
export { AvatarImage, type AvatarImageProps } from './avatar-image'
export { avatarAnatomy } from './avatar.anatomy'
