export type { OpenChangeDetails as CollapsibleOpenChangeDetails } from '@zag-js/collapsible'
export * as Collapsible from './collapsible'
export { CollapsibleContent, type CollapsibleContentProps } from './collapsible-content'
export { CollapsibleContext, type CollapsibleContextProps } from './collapsible-context'
export { CollapsibleRoot, type CollapsibleRootProps } from './collapsible-root'
export { CollapsibleTrigger, type CollapsibleTriggerProps } from './collapsible-trigger'
export { useCollapsibleContext, type UseCollapsibleContext } from './use-collapsible-context'
