// This file is generated by Velite

import type config from '../velite.config'

type Collections = typeof config.collections

export type Component = Collections['components']['schema']['_output']
export declare const components: Component[]
