// This file is generated by Velite

import type config from '../velite.config'

type Collections = typeof config.collections

export type Pages = Collections['pages']['schema']['_output']
export declare const pages: Pages[]
