export { avatarAnatomy } from '@ark-ui/angular/avatar'
export { collapsibleAnatomy } from '@ark-ui/angular/collapsible'
export { dialogAnatomy } from '@ark-ui/angular/dialog'
export { drawerAnatomy } from '@ark-ui/angular/drawer'
export { progressAnatomy } from '@ark-ui/angular/progress'
export { toggleAnatomy } from '@ark-ui/angular/toggle'
