export type { CopyStatusDetails as ClipboardCopyStatusDetails } from '@zag-js/clipboard'
export { ClipboardContext, type ClipboardContextProps } from './clipboard-context'
export { ClipboardControl, type ClipboardControlProps } from './clipboard-control'
export { ClipboardIndicator, type ClipboardIndicatorProps } from './clipboard-indicator'
export { ClipboardInput, type ClipboardInputProps } from './clipboard-input'
export { ClipboardLabel, type ClipboardLabelProps } from './clipboard-label'
export { ClipboardRoot, type ClipboardRootProps } from './clipboard-root'
export { ClipboardTrigger, type ClipboardTriggerProps } from './clipboard-trigger'
export { type UseClipboardContext, useClipboardContext } from './use-clipboard-context'

export * as Clipboard from './clipboard'
