name: 'Bug Report'
description: 'Submit a bug report'
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Kindly check for existing open or closed issues prior to submitting. 
        There's a possibility that your report has already been addressed! 😊
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'A brief description of the issue.'
      placeholder: |
        When I ____, I expected ____ to happen but ____ happened instead.
    validations:
      required: true
  - type: 'input'
    id: 'reproduction'
    attributes:
      label: 'Link to Reproduction (or Detailed Explanation)'
      description: |
        Provide a link to a CodeSandbox or Git repository which demonstrates the bug. If a link is not available, give a detailed explanation of the setup.
      placeholder: 'https:// or detailed setup explanation'
    validations:
      required: true
  - type: 'textarea'
    id: 'steps'
    attributes:
      label: 'Steps to Reproduce'
      description: |
        Explain how to trigger the issue in the provided reproduction.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: 'input'
    id: 'ark-version'
    attributes:
      label: 'Ark UI Version'
      description: 'The version of Ark UI you are using.'
      placeholder: 'e.g., 1.0.0'
    validations:
      required: true
  - type: 'checkboxes'
    id: 'framework'
    attributes:
      label: 'Framework'
      description: 'The framework in use (select all that apply)'
      options:
        - label: 'React'
        - label: 'Solid'
        - label: 'Vue'
  - type: 'input'
    id: 'browser'
    attributes:
      label: 'Browser'
      description: 'The browser(s) where this issue occurred (please specify version).'
      placeholder: 'e.g., Google Chrome, Firefox'
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: |
        Provide any additional information that might be helpful, such as screenshots, logs, error messages, or the impact of the bug. Links to relevant discussions or ideas are also welcome.
