blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://ark-ui.canny.io/
    about: Request, vote and explore new features
  - name: Questions & Discussions
    url: https://github.com/chakra-ui/ark/discussions
    about: Ask questions and discuss topics with other devlopers
  - name: Consult with the Maintainers (60m)
    url: https://calendly.com/chakra-ui/technical-consulting-60m
    about: Discuss your technical questions or feature request with the Ark UI Maintainers
