blank_issues_enabled: false
contact_links:
  - name: Request a feature or enhancement
    url: https://github.com/chakra-ui/ark/discussions/new?category=ideas
    about: Please post feature requests in GitHub Discussions
  - name: Questions & Discussions
    url: https://github.com/chakra-ui/ark/discussions
    about: Ask questions and discuss topics with other devlopers
