export type {
  Api as NumberInputApi,
  ElementIds as NumberInputElementIds,
  FocusChangeDetails as NumberInputFocusChangeDetails,
  HintValue as NumberInputHintValue,
  InputMode as NumberInputInputMode,
  IntlTranslations as NumberInputIntlTranslations,
  Machine as NumberInputMachine,
  Props as NumberInputMachineProps,
  Service as NumberInputService,
  ValidityState as NumberInputValidityState,
  ValueChangeDetails as NumberInputValueChangeDetails,
  ValueInvalidDetails as NumberInputValueInvalidDetails,
} from '@zag-js/number-input'
