// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/src/generate-example-registry.ts
// Run: pnpm --filter scripts generate-example-registry

import * as Accordion_Basic from '../../../packages/angular/src/accordion/examples/basic'
import * as Accordion_Collapsible from '../../../packages/angular/src/accordion/examples/collapsible'
import * as Accordion_Controlled from '../../../packages/angular/src/accordion/examples/controlled'
import * as Accordion_Disabled from '../../../packages/angular/src/accordion/examples/disabled'
import * as Accordion_Horizontal from '../../../packages/angular/src/accordion/examples/horizontal'
import * as Accordion_ItemContext from '../../../packages/angular/src/accordion/examples/item-context'
import * as Accordion_Multiple from '../../../packages/angular/src/accordion/examples/multiple'
import * as Accordion_RootProvider from '../../../packages/angular/src/accordion/examples/root-provider'
import * as Carousel_Autoplay from '../../../packages/angular/src/carousel/examples/autoplay'
import * as Carousel_Basic from '../../../packages/angular/src/carousel/examples/basic'
import * as Carousel_Controlled from '../../../packages/angular/src/carousel/examples/controlled'
import * as Carousel_DynamicSlides from '../../../packages/angular/src/carousel/examples/dynamic-slides'
import * as Carousel_RootProvider from '../../../packages/angular/src/carousel/examples/root-provider'
import * as Carousel_Vertical from '../../../packages/angular/src/carousel/examples/vertical'
import * as ClientOnly_Basic from '../../../packages/angular/src/client-only/examples/basic'
import * as ClientOnly_WithFallback from '../../../packages/angular/src/client-only/examples/with-fallback'
import * as Collapsible_Basic from '../../../packages/angular/src/collapsible/examples/basic'
import * as Collapsible_Disabled from '../../../packages/angular/src/collapsible/examples/disabled'
import * as Collapsible_Icons from '../../../packages/angular/src/collapsible/examples/icons'
import * as Collapsible_LazyMount from '../../../packages/angular/src/collapsible/examples/lazy-mount'
import * as Collapsible_Nested from '../../../packages/angular/src/collapsible/examples/nested'
import * as Collapsible_PartialCollapse from '../../../packages/angular/src/collapsible/examples/partial-collapse'
import * as Collapsible_RootProvider from '../../../packages/angular/src/collapsible/examples/root-provider'
import * as DateInput_Basic from '../../../packages/angular/src/date-input/examples/basic'
import * as DateInput_Controlled from '../../../packages/angular/src/date-input/examples/controlled'
import * as DateInput_Range from '../../../packages/angular/src/date-input/examples/range'
import * as DateInput_RootProvider from '../../../packages/angular/src/date-input/examples/root-provider'
import * as Dialog_AlertDialog from '../../../packages/angular/src/dialog/examples/alert-dialog'
import * as Dialog_Basic from '../../../packages/angular/src/dialog/examples/basic'
import * as Dialog_Controlled from '../../../packages/angular/src/dialog/examples/controlled'
import * as Dialog_DefaultOpen from '../../../packages/angular/src/dialog/examples/default-open'
import * as Dialog_Icons from '../../../packages/angular/src/dialog/examples/icons'
import * as Dialog_NonModal from '../../../packages/angular/src/dialog/examples/non-modal'
import * as Dialog_RootProvider from '../../../packages/angular/src/dialog/examples/root-provider'
import * as DownloadTrigger_Basic from '../../../packages/angular/src/download-trigger/examples/basic'
import * as DownloadTrigger_Svg from '../../../packages/angular/src/download-trigger/examples/svg'
import * as DownloadTrigger_WithPromise from '../../../packages/angular/src/download-trigger/examples/with-promise'
import * as Drawer_Basic from '../../../packages/angular/src/drawer/examples/basic'
import * as Drawer_Controlled from '../../../packages/angular/src/drawer/examples/controlled'
import * as Drawer_DefaultOpen from '../../../packages/angular/src/drawer/examples/default-open'
import * as Drawer_Icons from '../../../packages/angular/src/drawer/examples/icons'
import * as Drawer_RootProvider from '../../../packages/angular/src/drawer/examples/root-provider'
import * as Drawer_SwipeDirection from '../../../packages/angular/src/drawer/examples/swipe-direction'
import * as Drawer_WithTitleDescription from '../../../packages/angular/src/drawer/examples/with-title-description'
import * as FloatingPanel_AnchorPosition from '../../../packages/angular/src/floating-panel/examples/anchor-position'
import * as FloatingPanel_Basic from '../../../packages/angular/src/floating-panel/examples/basic'
import * as FloatingPanel_Context from '../../../packages/angular/src/floating-panel/examples/context'
import * as FloatingPanel_ControlledOpen from '../../../packages/angular/src/floating-panel/examples/controlled-open'
import * as FloatingPanel_ControlledPosition from '../../../packages/angular/src/floating-panel/examples/controlled-position'
import * as FloatingPanel_ControlledSize from '../../../packages/angular/src/floating-panel/examples/controlled-size'
import * as FloatingPanel_RootProvider from '../../../packages/angular/src/floating-panel/examples/root-provider'
import * as FocusTrap_Autofocus from '../../../packages/angular/src/focus-trap/examples/autofocus'
import * as FocusTrap_Basic from '../../../packages/angular/src/focus-trap/examples/basic'
import * as FocusTrap_InitialFocus from '../../../packages/angular/src/focus-trap/examples/initial-focus'
import * as Format_ByteBasic from '../../../packages/angular/src/format/examples/byte-basic'
import * as Format_ByteSizes from '../../../packages/angular/src/format/examples/byte-sizes'
import * as Format_ByteWithLocale from '../../../packages/angular/src/format/examples/byte-with-locale'
import * as Format_ByteWithUnitDisplay from '../../../packages/angular/src/format/examples/byte-with-unit-display'
import * as Format_ByteWithUnitSystem from '../../../packages/angular/src/format/examples/byte-with-unit-system'
import * as Format_ByteWithUnit from '../../../packages/angular/src/format/examples/byte-with-unit'
import * as Format_NumberBasic from '../../../packages/angular/src/format/examples/number-basic'
import * as Format_NumberWithCompact from '../../../packages/angular/src/format/examples/number-with-compact'
import * as Format_NumberWithCurrency from '../../../packages/angular/src/format/examples/number-with-currency'
import * as Format_NumberWithLocale from '../../../packages/angular/src/format/examples/number-with-locale'
import * as Format_NumberWithPercentage from '../../../packages/angular/src/format/examples/number-with-percentage'
import * as Format_NumberWithUnit from '../../../packages/angular/src/format/examples/number-with-unit'
import * as Format_RelativeTimeBasic from '../../../packages/angular/src/format/examples/relative-time-basic'
import * as Format_RelativeTimeShort from '../../../packages/angular/src/format/examples/relative-time-short'
import * as Format_TimeBasic from '../../../packages/angular/src/format/examples/time-basic'
import * as Format_TimeWithAmPmLabels from '../../../packages/angular/src/format/examples/time-with-am-pm-labels'
import * as Format_TimeWithDate from '../../../packages/angular/src/format/examples/time-with-date'
import * as Format_TimeWithLocale from '../../../packages/angular/src/format/examples/time-with-locale'
import * as Format_TimeWithSeconds from '../../../packages/angular/src/format/examples/time-with-seconds'
import * as Frame_Basic from '../../../packages/angular/src/frame/examples/basic'
import * as Frame_InheritStyles from '../../../packages/angular/src/frame/examples/inherit-styles'
import * as Frame_Script from '../../../packages/angular/src/frame/examples/script'
import * as Frame_SrcDoc from '../../../packages/angular/src/frame/examples/src-doc'
import * as Highlight_Basic from '../../../packages/angular/src/highlight/examples/basic'
import * as Highlight_DynamicQuery from '../../../packages/angular/src/highlight/examples/dynamic-query'
import * as Highlight_ExactMatch from '../../../packages/angular/src/highlight/examples/exact-match'
import * as Highlight_IgnoreCase from '../../../packages/angular/src/highlight/examples/ignore-case'
import * as Highlight_MatchAll from '../../../packages/angular/src/highlight/examples/match-all'
import * as Highlight_Multiple from '../../../packages/angular/src/highlight/examples/multiple'
import * as Highlight_RepeatingText from '../../../packages/angular/src/highlight/examples/repeating-text'
import * as HoverCard_Basic from '../../../packages/angular/src/hover-card/examples/basic'
import * as HoverCard_Controlled from '../../../packages/angular/src/hover-card/examples/controlled'
import * as HoverCard_Delay from '../../../packages/angular/src/hover-card/examples/delay'
import * as HoverCard_MultipleTriggers from '../../../packages/angular/src/hover-card/examples/multiple-triggers'
import * as HoverCard_Positioning from '../../../packages/angular/src/hover-card/examples/positioning'
import * as HoverCard_RootProvider from '../../../packages/angular/src/hover-card/examples/root-provider'
import * as ImageCropper_Basic from '../../../packages/angular/src/image-cropper/examples/basic'
import * as ImageCropper_Controlled from '../../../packages/angular/src/image-cropper/examples/controlled'
import * as ImageCropper_RootProvider from '../../../packages/angular/src/image-cropper/examples/root-provider'
import * as JsonTreeView_Basic from '../../../packages/angular/src/json-tree-view/examples/basic'
import * as JsonTreeView_DataTypes from '../../../packages/angular/src/json-tree-view/examples/data-types'
import * as JsonTreeView_RenderValue from '../../../packages/angular/src/json-tree-view/examples/render-value'
import * as JsonTreeView_RootProvider from '../../../packages/angular/src/json-tree-view/examples/root-provider'
import * as Marquee_AutoFill from '../../../packages/angular/src/marquee/examples/auto-fill'
import * as Marquee_Basic from '../../../packages/angular/src/marquee/examples/basic'
import * as Marquee_FiniteLoops from '../../../packages/angular/src/marquee/examples/finite-loops'
import * as Marquee_PauseOnInteraction from '../../../packages/angular/src/marquee/examples/pause-on-interaction'
import * as Marquee_ProgrammaticControl from '../../../packages/angular/src/marquee/examples/programmatic-control'
import * as Marquee_Reverse from '../../../packages/angular/src/marquee/examples/reverse'
import * as Marquee_RootProvider from '../../../packages/angular/src/marquee/examples/root-provider'
import * as Marquee_Speed from '../../../packages/angular/src/marquee/examples/speed'
import * as Marquee_Vertical from '../../../packages/angular/src/marquee/examples/vertical'
import * as Marquee_WithEdges from '../../../packages/angular/src/marquee/examples/with-edges'
import * as Menu_Basic from '../../../packages/angular/src/menu/examples/basic'
import * as Menu_CheckboxItems from '../../../packages/angular/src/menu/examples/checkbox-items'
import * as Menu_ControlledHighlight from '../../../packages/angular/src/menu/examples/controlled-highlight'
import * as Menu_Controlled from '../../../packages/angular/src/menu/examples/controlled'
import * as Menu_Icons from '../../../packages/angular/src/menu/examples/icons'
import * as Menu_ItemGroup from '../../../packages/angular/src/menu/examples/item-group'
import * as Menu_NestedSubmenu from '../../../packages/angular/src/menu/examples/nested-submenu'
import * as Menu_RadioItems from '../../../packages/angular/src/menu/examples/radio-items'
import * as Menu_RootProvider from '../../../packages/angular/src/menu/examples/root-provider'
import * as Menu_WithSeparator from '../../../packages/angular/src/menu/examples/with-separator'
import * as NavigationMenu_Basic from '../../../packages/angular/src/navigation-menu/examples/basic'
import * as NavigationMenu_Controlled from '../../../packages/angular/src/navigation-menu/examples/controlled'
import * as NavigationMenu_Icons from '../../../packages/angular/src/navigation-menu/examples/icons'
import * as NavigationMenu_RootProvider from '../../../packages/angular/src/navigation-menu/examples/root-provider'
import * as NavigationMenu_Viewport from '../../../packages/angular/src/navigation-menu/examples/viewport'
import * as NavigationMenu_WithIndicator from '../../../packages/angular/src/navigation-menu/examples/with-indicator'
import * as Pagination_Basic from '../../../packages/angular/src/pagination/examples/basic'
import * as Pagination_Controlled from '../../../packages/angular/src/pagination/examples/controlled'
import * as Pagination_PageSizeControl from '../../../packages/angular/src/pagination/examples/page-size-control'
import * as Pagination_RootProvider from '../../../packages/angular/src/pagination/examples/root-provider'
import * as Pagination_WithEdges from '../../../packages/angular/src/pagination/examples/with-edges'
import * as Popover_Anchor from '../../../packages/angular/src/popover/examples/anchor'
import * as Popover_Arrow from '../../../packages/angular/src/popover/examples/arrow'
import * as Popover_Basic from '../../../packages/angular/src/popover/examples/basic'
import * as Popover_Controlled from '../../../packages/angular/src/popover/examples/controlled'
import * as Popover_DefaultOpen from '../../../packages/angular/src/popover/examples/default-open'
import * as Popover_Icons from '../../../packages/angular/src/popover/examples/icons'
import * as Popover_Modal from '../../../packages/angular/src/popover/examples/modal'
import * as Popover_RootProvider from '../../../packages/angular/src/popover/examples/root-provider'
import * as Presence_Basic from '../../../packages/angular/src/presence/examples/basic'
import * as Presence_LazyMountAndUnmountOnExit from '../../../packages/angular/src/presence/examples/lazy-mount-and-unmount-on-exit'
import * as Presence_LazyMount from '../../../packages/angular/src/presence/examples/lazy-mount'
import * as Presence_SkipAnimationOnMount from '../../../packages/angular/src/presence/examples/skip-animation-on-mount'
import * as Presence_UnmountOnExit from '../../../packages/angular/src/presence/examples/unmount-on-exit'
import * as QrCode_Basic from '../../../packages/angular/src/qr-code/examples/basic'
import * as QrCode_Controlled from '../../../packages/angular/src/qr-code/examples/controlled'
import * as QrCode_Download from '../../../packages/angular/src/qr-code/examples/download'
import * as QrCode_Overlay from '../../../packages/angular/src/qr-code/examples/overlay'
import * as QrCode_RootProvider from '../../../packages/angular/src/qr-code/examples/root-provider'
import * as ScrollArea_Basic from '../../../packages/angular/src/scroll-area/examples/basic'
import * as ScrollArea_BothDirections from '../../../packages/angular/src/scroll-area/examples/both-directions'
import * as ScrollArea_Horizontal from '../../../packages/angular/src/scroll-area/examples/horizontal'
import * as ScrollArea_Nested from '../../../packages/angular/src/scroll-area/examples/nested'
import * as ScrollArea_RootProvider from '../../../packages/angular/src/scroll-area/examples/root-provider'
import * as SignaturePad_Basic from '../../../packages/angular/src/signature-pad/examples/basic'
import * as SignaturePad_ImagePreview from '../../../packages/angular/src/signature-pad/examples/image-preview'
import * as SignaturePad_RootProvider from '../../../packages/angular/src/signature-pad/examples/root-provider'
import * as Splitter_Basic from '../../../packages/angular/src/splitter/examples/basic'
import * as Splitter_Collapsible from '../../../packages/angular/src/splitter/examples/collapsible'
import * as Splitter_Context from '../../../packages/angular/src/splitter/examples/context'
import * as Splitter_MultiplePanels from '../../../packages/angular/src/splitter/examples/multiple-panels'
import * as Splitter_Nested from '../../../packages/angular/src/splitter/examples/nested'
import * as Splitter_ResizeIndicator from '../../../packages/angular/src/splitter/examples/resize-indicator'
import * as Splitter_RootProvider from '../../../packages/angular/src/splitter/examples/root-provider'
import * as Splitter_Vertical from '../../../packages/angular/src/splitter/examples/vertical'
import * as Steps_Basic from '../../../packages/angular/src/steps/examples/basic'
import * as Steps_Controlled from '../../../packages/angular/src/steps/examples/controlled'
import * as Steps_RootProvider from '../../../packages/angular/src/steps/examples/root-provider'
import * as Steps_Vertical from '../../../packages/angular/src/steps/examples/vertical'
import * as Swap_Fade from '../../../packages/angular/src/swap/examples/fade'
import * as Swap_Flip from '../../../packages/angular/src/swap/examples/flip'
import * as Swap_Rotate from '../../../packages/angular/src/swap/examples/rotate'
import * as Swap_Scale from '../../../packages/angular/src/swap/examples/scale'
import * as Tabs_Basic from '../../../packages/angular/src/tabs/examples/basic'
import * as Tabs_Controlled from '../../../packages/angular/src/tabs/examples/controlled'
import * as Tabs_DisabledTab from '../../../packages/angular/src/tabs/examples/disabled-tab'
import * as Tabs_Indicator from '../../../packages/angular/src/tabs/examples/indicator'
import * as Tabs_ManualActivation from '../../../packages/angular/src/tabs/examples/manual-activation'
import * as Tabs_RootProvider from '../../../packages/angular/src/tabs/examples/root-provider'
import * as Tabs_Vertical from '../../../packages/angular/src/tabs/examples/vertical'
import * as Timer_Basic from '../../../packages/angular/src/timer/examples/basic'
import * as Timer_Countdown from '../../../packages/angular/src/timer/examples/countdown'
import * as Timer_Events from '../../../packages/angular/src/timer/examples/events'
import * as Timer_Interval from '../../../packages/angular/src/timer/examples/interval'
import * as Timer_Pomodoro from '../../../packages/angular/src/timer/examples/pomodoro'
import * as Timer_RootProvider from '../../../packages/angular/src/timer/examples/root-provider'
import * as Toast_Action from '../../../packages/angular/src/toast/examples/action'
import * as Toast_Basic from '../../../packages/angular/src/toast/examples/basic'
import * as Toast_Duration from '../../../packages/angular/src/toast/examples/duration'
import * as Toast_MaxToasts from '../../../packages/angular/src/toast/examples/max-toasts'
import * as Toast_Placement from '../../../packages/angular/src/toast/examples/placement'
import * as Toast_Update from '../../../packages/angular/src/toast/examples/update'
import * as Tooltip_Arrow from '../../../packages/angular/src/tooltip/examples/arrow'
import * as Tooltip_Basic from '../../../packages/angular/src/tooltip/examples/basic'
import * as Tooltip_Controlled from '../../../packages/angular/src/tooltip/examples/controlled'
import * as Tooltip_Delay from '../../../packages/angular/src/tooltip/examples/delay'
import * as Tooltip_Interactive from '../../../packages/angular/src/tooltip/examples/interactive'
import * as Tooltip_Positioning from '../../../packages/angular/src/tooltip/examples/positioning'
import * as Tooltip_RootProvider from '../../../packages/angular/src/tooltip/examples/root-provider'
import * as Tour_Basic from '../../../packages/angular/src/tour/examples/basic'
import * as Tour_Controlled from '../../../packages/angular/src/tour/examples/controlled'
import * as Tour_WaitForClick from '../../../packages/angular/src/tour/examples/wait-for-click'
import * as TreeView_AsyncLoading from '../../../packages/angular/src/tree-view/examples/async-loading'
import * as TreeView_Basic from '../../../packages/angular/src/tree-view/examples/basic'
import * as TreeView_CheckboxTree from '../../../packages/angular/src/tree-view/examples/checkbox-tree'
import * as TreeView_ControlledExpanded from '../../../packages/angular/src/tree-view/examples/controlled-expanded'
import * as TreeView_ControlledSelected from '../../../packages/angular/src/tree-view/examples/controlled-selected'
import * as TreeView_ExpandCollapseAll from '../../../packages/angular/src/tree-view/examples/expand-collapse-all'
import * as TreeView_RenameNode from '../../../packages/angular/src/tree-view/examples/rename-node'
import * as TreeView_RootProvider from '../../../packages/angular/src/tree-view/examples/root-provider'

// Registry maps Angular example keys to their module namespace.
type AngularExampleModule = Record<string, unknown>
type AngularExampleEntry = {
  module: AngularExampleModule
  exportName: string
}

const angularExampleModules: Record<string, AngularExampleEntry> = {
  'accordion/basic': { module: Accordion_Basic, exportName: 'AccordionBasicExample' },
  'accordion/collapsible': { module: Accordion_Collapsible, exportName: 'AccordionCollapsibleExample' },
  'accordion/controlled': { module: Accordion_Controlled, exportName: 'AccordionControlledExample' },
  'accordion/disabled': { module: Accordion_Disabled, exportName: 'AccordionDisabledExample' },
  'accordion/horizontal': { module: Accordion_Horizontal, exportName: 'AccordionHorizontalExample' },
  'accordion/item-context': { module: Accordion_ItemContext, exportName: 'AccordionItemContextExample' },
  'accordion/multiple': { module: Accordion_Multiple, exportName: 'AccordionMultipleExample' },
  'accordion/root-provider': { module: Accordion_RootProvider, exportName: 'AccordionRootProviderExample' },
  'carousel/autoplay': { module: Carousel_Autoplay, exportName: 'CarouselAutoplayExample' },
  'carousel/basic': { module: Carousel_Basic, exportName: 'CarouselBasicExample' },
  'carousel/controlled': { module: Carousel_Controlled, exportName: 'CarouselControlledExample' },
  'carousel/dynamic-slides': { module: Carousel_DynamicSlides, exportName: 'CarouselDynamicSlidesExample' },
  'carousel/root-provider': { module: Carousel_RootProvider, exportName: 'CarouselRootProviderExample' },
  'carousel/vertical': { module: Carousel_Vertical, exportName: 'CarouselVerticalExample' },
  'client-only/basic': { module: ClientOnly_Basic, exportName: 'ClientOnlyBasicExample' },
  'client-only/with-fallback': { module: ClientOnly_WithFallback, exportName: 'ClientOnlyWithFallbackExample' },
  'collapsible/basic': { module: Collapsible_Basic, exportName: 'CollapsibleBasicExample' },
  'collapsible/disabled': { module: Collapsible_Disabled, exportName: 'CollapsibleDisabledExample' },
  'collapsible/icons': { module: Collapsible_Icons, exportName: 'CollapsibleIconsExample' },
  'collapsible/lazy-mount': { module: Collapsible_LazyMount, exportName: 'CollapsibleLazyMountExample' },
  'collapsible/nested': { module: Collapsible_Nested, exportName: 'CollapsibleNestedExample' },
  'collapsible/partial-collapse': {
    module: Collapsible_PartialCollapse,
    exportName: 'CollapsiblePartialCollapseExample',
  },
  'collapsible/root-provider': { module: Collapsible_RootProvider, exportName: 'CollapsibleRootProviderExample' },
  'date-input/basic': { module: DateInput_Basic, exportName: 'DateInputBasicExample' },
  'date-input/controlled': { module: DateInput_Controlled, exportName: 'DateInputControlledExample' },
  'date-input/range': { module: DateInput_Range, exportName: 'DateInputRangeExample' },
  'date-input/root-provider': { module: DateInput_RootProvider, exportName: 'DateInputRootProviderExample' },
  'dialog/alert-dialog': { module: Dialog_AlertDialog, exportName: 'DialogAlertDialogExample' },
  'dialog/basic': { module: Dialog_Basic, exportName: 'DialogBasicExample' },
  'dialog/controlled': { module: Dialog_Controlled, exportName: 'DialogControlledExample' },
  'dialog/default-open': { module: Dialog_DefaultOpen, exportName: 'DialogDefaultOpenExample' },
  'dialog/icons': { module: Dialog_Icons, exportName: 'DialogIconsExample' },
  'dialog/non-modal': { module: Dialog_NonModal, exportName: 'DialogNonModalExample' },
  'dialog/root-provider': { module: Dialog_RootProvider, exportName: 'DialogRootProviderExample' },
  'download-trigger/basic': { module: DownloadTrigger_Basic, exportName: 'DownloadTriggerBasicExample' },
  'download-trigger/svg': { module: DownloadTrigger_Svg, exportName: 'DownloadTriggerSvgExample' },
  'download-trigger/with-promise': {
    module: DownloadTrigger_WithPromise,
    exportName: 'DownloadTriggerWithPromiseExample',
  },
  'drawer/basic': { module: Drawer_Basic, exportName: 'DrawerBasicExample' },
  'drawer/controlled': { module: Drawer_Controlled, exportName: 'DrawerControlledExample' },
  'drawer/default-open': { module: Drawer_DefaultOpen, exportName: 'DrawerDefaultOpenExample' },
  'drawer/icons': { module: Drawer_Icons, exportName: 'DrawerIconsExample' },
  'drawer/root-provider': { module: Drawer_RootProvider, exportName: 'DrawerRootProviderExample' },
  'drawer/swipe-direction': { module: Drawer_SwipeDirection, exportName: 'DrawerSwipeDirectionExample' },
  'drawer/with-title-description': {
    module: Drawer_WithTitleDescription,
    exportName: 'DrawerWithTitleDescriptionExample',
  },
  'floating-panel/anchor-position': {
    module: FloatingPanel_AnchorPosition,
    exportName: 'FloatingPanelAnchorPositionExample',
  },
  'floating-panel/basic': { module: FloatingPanel_Basic, exportName: 'FloatingPanelBasicExample' },
  'floating-panel/context': { module: FloatingPanel_Context, exportName: 'FloatingPanelContextExample' },
  'floating-panel/controlled-open': {
    module: FloatingPanel_ControlledOpen,
    exportName: 'FloatingPanelControlledOpenExample',
  },
  'floating-panel/controlled-position': {
    module: FloatingPanel_ControlledPosition,
    exportName: 'FloatingPanelControlledPositionExample',
  },
  'floating-panel/controlled-size': {
    module: FloatingPanel_ControlledSize,
    exportName: 'FloatingPanelControlledSizeExample',
  },
  'floating-panel/root-provider': {
    module: FloatingPanel_RootProvider,
    exportName: 'FloatingPanelRootProviderExample',
  },
  'focus-trap/autofocus': { module: FocusTrap_Autofocus, exportName: 'FocusTrapAutofocusExample' },
  'focus-trap/basic': { module: FocusTrap_Basic, exportName: 'FocusTrapBasicExample' },
  'focus-trap/initial-focus': { module: FocusTrap_InitialFocus, exportName: 'FocusTrapInitialFocusExample' },
  'format/byte-basic': { module: Format_ByteBasic, exportName: 'FormatByteBasicExample' },
  'format/byte-sizes': { module: Format_ByteSizes, exportName: 'FormatByteSizesExample' },
  'format/byte-with-locale': { module: Format_ByteWithLocale, exportName: 'FormatByteWithLocaleExample' },
  'format/byte-with-unit-display': {
    module: Format_ByteWithUnitDisplay,
    exportName: 'FormatByteWithUnitDisplayExample',
  },
  'format/byte-with-unit-system': { module: Format_ByteWithUnitSystem, exportName: 'FormatByteWithUnitSystemExample' },
  'format/byte-with-unit': { module: Format_ByteWithUnit, exportName: 'FormatByteWithUnitExample' },
  'format/number-basic': { module: Format_NumberBasic, exportName: 'FormatNumberBasicExample' },
  'format/number-with-compact': { module: Format_NumberWithCompact, exportName: 'FormatNumberWithCompactExample' },
  'format/number-with-currency': { module: Format_NumberWithCurrency, exportName: 'FormatNumberWithCurrencyExample' },
  'format/number-with-locale': { module: Format_NumberWithLocale, exportName: 'FormatNumberWithLocaleExample' },
  'format/number-with-percentage': {
    module: Format_NumberWithPercentage,
    exportName: 'FormatNumberWithPercentageExample',
  },
  'format/number-with-unit': { module: Format_NumberWithUnit, exportName: 'FormatNumberWithUnitExample' },
  'format/relative-time-basic': { module: Format_RelativeTimeBasic, exportName: 'FormatRelativeTimeBasicExample' },
  'format/relative-time-short': { module: Format_RelativeTimeShort, exportName: 'FormatRelativeTimeShortExample' },
  'format/time-basic': { module: Format_TimeBasic, exportName: 'FormatTimeBasicExample' },
  'format/time-with-am-pm-labels': { module: Format_TimeWithAmPmLabels, exportName: 'FormatTimeWithAmPmLabelsExample' },
  'format/time-with-date': { module: Format_TimeWithDate, exportName: 'FormatTimeWithDateExample' },
  'format/time-with-locale': { module: Format_TimeWithLocale, exportName: 'FormatTimeWithLocaleExample' },
  'format/time-with-seconds': { module: Format_TimeWithSeconds, exportName: 'FormatTimeWithSecondsExample' },
  'frame/basic': { module: Frame_Basic, exportName: 'FrameBasicExample' },
  'frame/inherit-styles': { module: Frame_InheritStyles, exportName: 'FrameInheritStylesExample' },
  'frame/script': { module: Frame_Script, exportName: 'FrameScriptExample' },
  'frame/src-doc': { module: Frame_SrcDoc, exportName: 'FrameSrcDocExample' },
  'highlight/basic': { module: Highlight_Basic, exportName: 'HighlightBasicExample' },
  'highlight/dynamic-query': { module: Highlight_DynamicQuery, exportName: 'HighlightDynamicQueryExample' },
  'highlight/exact-match': { module: Highlight_ExactMatch, exportName: 'HighlightExactMatchExample' },
  'highlight/ignore-case': { module: Highlight_IgnoreCase, exportName: 'HighlightIgnoreCaseExample' },
  'highlight/match-all': { module: Highlight_MatchAll, exportName: 'HighlightMatchAllExample' },
  'highlight/multiple': { module: Highlight_Multiple, exportName: 'HighlightMultipleExample' },
  'highlight/repeating-text': { module: Highlight_RepeatingText, exportName: 'HighlightRepeatingTextExample' },
  'hover-card/basic': { module: HoverCard_Basic, exportName: 'HoverCardBasicExample' },
  'hover-card/controlled': { module: HoverCard_Controlled, exportName: 'HoverCardControlledExample' },
  'hover-card/delay': { module: HoverCard_Delay, exportName: 'HoverCardDelayExample' },
  'hover-card/multiple-triggers': {
    module: HoverCard_MultipleTriggers,
    exportName: 'HoverCardMultipleTriggersExample',
  },
  'hover-card/positioning': { module: HoverCard_Positioning, exportName: 'HoverCardPositioningExample' },
  'hover-card/root-provider': { module: HoverCard_RootProvider, exportName: 'HoverCardRootProviderExample' },
  'image-cropper/basic': { module: ImageCropper_Basic, exportName: 'ImageCropperBasicExample' },
  'image-cropper/controlled': { module: ImageCropper_Controlled, exportName: 'ImageCropperControlledExample' },
  'image-cropper/root-provider': { module: ImageCropper_RootProvider, exportName: 'ImageCropperRootProviderExample' },
  'json-tree-view/basic': { module: JsonTreeView_Basic, exportName: 'JsonTreeViewBasicExample' },
  'json-tree-view/data-types': { module: JsonTreeView_DataTypes, exportName: 'JsonTreeViewDataTypesExample' },
  'json-tree-view/render-value': { module: JsonTreeView_RenderValue, exportName: 'JsonTreeViewRenderValueExample' },
  'json-tree-view/root-provider': { module: JsonTreeView_RootProvider, exportName: 'JsonTreeViewRootProviderExample' },
  'marquee/auto-fill': { module: Marquee_AutoFill, exportName: 'MarqueeAutoFillExample' },
  'marquee/basic': { module: Marquee_Basic, exportName: 'MarqueeBasicExample' },
  'marquee/finite-loops': { module: Marquee_FiniteLoops, exportName: 'MarqueeFiniteLoopsExample' },
  'marquee/pause-on-interaction': {
    module: Marquee_PauseOnInteraction,
    exportName: 'MarqueePauseOnInteractionExample',
  },
  'marquee/programmatic-control': {
    module: Marquee_ProgrammaticControl,
    exportName: 'MarqueeProgrammaticControlExample',
  },
  'marquee/reverse': { module: Marquee_Reverse, exportName: 'MarqueeReverseExample' },
  'marquee/root-provider': { module: Marquee_RootProvider, exportName: 'MarqueeRootProviderExample' },
  'marquee/speed': { module: Marquee_Speed, exportName: 'MarqueeSpeedExample' },
  'marquee/vertical': { module: Marquee_Vertical, exportName: 'MarqueeVerticalExample' },
  'marquee/with-edges': { module: Marquee_WithEdges, exportName: 'MarqueeWithEdgesExample' },
  'menu/basic': { module: Menu_Basic, exportName: 'MenuBasicExample' },
  'menu/checkbox-items': { module: Menu_CheckboxItems, exportName: 'MenuCheckboxItemsExample' },
  'menu/controlled-highlight': { module: Menu_ControlledHighlight, exportName: 'MenuControlledHighlightExample' },
  'menu/controlled': { module: Menu_Controlled, exportName: 'MenuControlledExample' },
  'menu/icons': { module: Menu_Icons, exportName: 'MenuIconsExample' },
  'menu/item-group': { module: Menu_ItemGroup, exportName: 'MenuItemGroupExample' },
  'menu/nested-submenu': { module: Menu_NestedSubmenu, exportName: 'MenuNestedSubmenuExample' },
  'menu/radio-items': { module: Menu_RadioItems, exportName: 'MenuRadioItemsExample' },
  'menu/root-provider': { module: Menu_RootProvider, exportName: 'MenuRootProviderExample' },
  'menu/with-separator': { module: Menu_WithSeparator, exportName: 'MenuWithSeparatorExample' },
  'navigation-menu/basic': { module: NavigationMenu_Basic, exportName: 'NavigationMenuBasicExample' },
  'navigation-menu/controlled': { module: NavigationMenu_Controlled, exportName: 'NavigationMenuControlledExample' },
  'navigation-menu/icons': { module: NavigationMenu_Icons, exportName: 'NavigationMenuIconsExample' },
  'navigation-menu/root-provider': {
    module: NavigationMenu_RootProvider,
    exportName: 'NavigationMenuRootProviderExample',
  },
  'navigation-menu/viewport': { module: NavigationMenu_Viewport, exportName: 'NavigationMenuViewportExample' },
  'navigation-menu/with-indicator': {
    module: NavigationMenu_WithIndicator,
    exportName: 'NavigationMenuWithIndicatorExample',
  },
  'pagination/basic': { module: Pagination_Basic, exportName: 'PaginationBasicExample' },
  'pagination/controlled': { module: Pagination_Controlled, exportName: 'PaginationControlledExample' },
  'pagination/page-size-control': {
    module: Pagination_PageSizeControl,
    exportName: 'PaginationPageSizeControlExample',
  },
  'pagination/root-provider': { module: Pagination_RootProvider, exportName: 'PaginationRootProviderExample' },
  'pagination/with-edges': { module: Pagination_WithEdges, exportName: 'PaginationWithEdgesExample' },
  'popover/anchor': { module: Popover_Anchor, exportName: 'PopoverAnchorExample' },
  'popover/arrow': { module: Popover_Arrow, exportName: 'PopoverArrowExample' },
  'popover/basic': { module: Popover_Basic, exportName: 'PopoverBasicExample' },
  'popover/controlled': { module: Popover_Controlled, exportName: 'PopoverControlledExample' },
  'popover/default-open': { module: Popover_DefaultOpen, exportName: 'PopoverDefaultOpenExample' },
  'popover/icons': { module: Popover_Icons, exportName: 'PopoverIconsExample' },
  'popover/modal': { module: Popover_Modal, exportName: 'PopoverModalExample' },
  'popover/root-provider': { module: Popover_RootProvider, exportName: 'PopoverRootProviderExample' },
  'presence/basic': { module: Presence_Basic, exportName: 'PresenceBasicExample' },
  'presence/lazy-mount-and-unmount-on-exit': {
    module: Presence_LazyMountAndUnmountOnExit,
    exportName: 'PresenceLazyMountAndUnmountOnExitExample',
  },
  'presence/lazy-mount': { module: Presence_LazyMount, exportName: 'PresenceLazyMountExample' },
  'presence/skip-animation-on-mount': {
    module: Presence_SkipAnimationOnMount,
    exportName: 'PresenceSkipAnimationOnMountExample',
  },
  'presence/unmount-on-exit': { module: Presence_UnmountOnExit, exportName: 'PresenceUnmountOnExitExample' },
  'qr-code/basic': { module: QrCode_Basic, exportName: 'QrCodeBasicExample' },
  'qr-code/controlled': { module: QrCode_Controlled, exportName: 'QrCodeControlledExample' },
  'qr-code/download': { module: QrCode_Download, exportName: 'QrCodeDownloadExample' },
  'qr-code/overlay': { module: QrCode_Overlay, exportName: 'QrCodeOverlayExample' },
  'qr-code/root-provider': { module: QrCode_RootProvider, exportName: 'QrCodeRootProviderExample' },
  'scroll-area/basic': { module: ScrollArea_Basic, exportName: 'ScrollAreaBasicExample' },
  'scroll-area/both-directions': { module: ScrollArea_BothDirections, exportName: 'ScrollAreaBothDirectionsExample' },
  'scroll-area/horizontal': { module: ScrollArea_Horizontal, exportName: 'ScrollAreaHorizontalExample' },
  'scroll-area/nested': { module: ScrollArea_Nested, exportName: 'ScrollAreaNestedExample' },
  'scroll-area/root-provider': { module: ScrollArea_RootProvider, exportName: 'ScrollAreaRootProviderExample' },
  'signature-pad/basic': { module: SignaturePad_Basic, exportName: 'SignaturePadBasicExample' },
  'signature-pad/image-preview': { module: SignaturePad_ImagePreview, exportName: 'SignaturePadImagePreviewExample' },
  'signature-pad/root-provider': { module: SignaturePad_RootProvider, exportName: 'SignaturePadRootProviderExample' },
  'splitter/basic': { module: Splitter_Basic, exportName: 'SplitterBasicExample' },
  'splitter/collapsible': { module: Splitter_Collapsible, exportName: 'SplitterCollapsibleExample' },
  'splitter/context': { module: Splitter_Context, exportName: 'SplitterContextExample' },
  'splitter/multiple-panels': { module: Splitter_MultiplePanels, exportName: 'SplitterMultiplePanelsExample' },
  'splitter/nested': { module: Splitter_Nested, exportName: 'SplitterNestedExample' },
  'splitter/resize-indicator': { module: Splitter_ResizeIndicator, exportName: 'SplitterResizeIndicatorExample' },
  'splitter/root-provider': { module: Splitter_RootProvider, exportName: 'SplitterRootProviderExample' },
  'splitter/vertical': { module: Splitter_Vertical, exportName: 'SplitterVerticalExample' },
  'steps/basic': { module: Steps_Basic, exportName: 'StepsBasicExample' },
  'steps/controlled': { module: Steps_Controlled, exportName: 'StepsControlledExample' },
  'steps/root-provider': { module: Steps_RootProvider, exportName: 'StepsRootProviderExample' },
  'steps/vertical': { module: Steps_Vertical, exportName: 'StepsVerticalExample' },
  'swap/fade': { module: Swap_Fade, exportName: 'SwapFadeExample' },
  'swap/flip': { module: Swap_Flip, exportName: 'SwapFlipExample' },
  'swap/rotate': { module: Swap_Rotate, exportName: 'SwapRotateExample' },
  'swap/scale': { module: Swap_Scale, exportName: 'SwapScaleExample' },
  'tabs/basic': { module: Tabs_Basic, exportName: 'TabsBasicExample' },
  'tabs/controlled': { module: Tabs_Controlled, exportName: 'TabsControlledExample' },
  'tabs/disabled-tab': { module: Tabs_DisabledTab, exportName: 'TabsDisabledTabExample' },
  'tabs/indicator': { module: Tabs_Indicator, exportName: 'TabsIndicatorExample' },
  'tabs/manual-activation': { module: Tabs_ManualActivation, exportName: 'TabsManualActivationExample' },
  'tabs/root-provider': { module: Tabs_RootProvider, exportName: 'TabsRootProviderExample' },
  'tabs/vertical': { module: Tabs_Vertical, exportName: 'TabsVerticalExample' },
  'timer/basic': { module: Timer_Basic, exportName: 'TimerBasicExample' },
  'timer/countdown': { module: Timer_Countdown, exportName: 'TimerCountdownExample' },
  'timer/events': { module: Timer_Events, exportName: 'TimerEventsExample' },
  'timer/interval': { module: Timer_Interval, exportName: 'TimerIntervalExample' },
  'timer/pomodoro': { module: Timer_Pomodoro, exportName: 'TimerPomodoroExample' },
  'timer/root-provider': { module: Timer_RootProvider, exportName: 'TimerRootProviderExample' },
  'toast/action': { module: Toast_Action, exportName: 'ToastActionExample' },
  'toast/basic': { module: Toast_Basic, exportName: 'ToastBasicExample' },
  'toast/duration': { module: Toast_Duration, exportName: 'ToastDurationExample' },
  'toast/max-toasts': { module: Toast_MaxToasts, exportName: 'ToastMaxToastsExample' },
  'toast/placement': { module: Toast_Placement, exportName: 'ToastPlacementExample' },
  'toast/update': { module: Toast_Update, exportName: 'ToastUpdateExample' },
  'tooltip/arrow': { module: Tooltip_Arrow, exportName: 'TooltipArrowExample' },
  'tooltip/basic': { module: Tooltip_Basic, exportName: 'TooltipBasicExample' },
  'tooltip/controlled': { module: Tooltip_Controlled, exportName: 'TooltipControlledExample' },
  'tooltip/delay': { module: Tooltip_Delay, exportName: 'TooltipDelayExample' },
  'tooltip/interactive': { module: Tooltip_Interactive, exportName: 'TooltipInteractiveExample' },
  'tooltip/positioning': { module: Tooltip_Positioning, exportName: 'TooltipPositioningExample' },
  'tooltip/root-provider': { module: Tooltip_RootProvider, exportName: 'TooltipRootProviderExample' },
  'tour/basic': { module: Tour_Basic, exportName: 'TourBasicExample' },
  'tour/controlled': { module: Tour_Controlled, exportName: 'TourControlledExample' },
  'tour/wait-for-click': { module: Tour_WaitForClick, exportName: 'TourWaitForClickExample' },
  'tree-view/async-loading': { module: TreeView_AsyncLoading, exportName: 'TreeViewAsyncLoadingExample' },
  'tree-view/basic': { module: TreeView_Basic, exportName: 'TreeViewBasicExample' },
  'tree-view/checkbox-tree': { module: TreeView_CheckboxTree, exportName: 'TreeViewCheckboxTreeExample' },
  'tree-view/controlled-expanded': {
    module: TreeView_ControlledExpanded,
    exportName: 'TreeViewControlledExpandedExample',
  },
  'tree-view/controlled-selected': {
    module: TreeView_ControlledSelected,
    exportName: 'TreeViewControlledSelectedExample',
  },
  'tree-view/expand-collapse-all': {
    module: TreeView_ExpandCollapseAll,
    exportName: 'TreeViewExpandCollapseAllExample',
  },
  'tree-view/rename-node': { module: TreeView_RenameNode, exportName: 'TreeViewRenameNodeExample' },
  'tree-view/root-provider': { module: TreeView_RootProvider, exportName: 'TreeViewRootProviderExample' },
}

/**
 * Get the Angular component export from a module
 */
function getComponentFromModule(entry: AngularExampleEntry): unknown {
  const value = entry.module[entry.exportName]
  return typeof value === 'function' ? value : undefined
}

/**
 * Get an Angular example component by component name and example id
 */
export function getAngularExample(component: string, example: string): unknown {
  const entry = angularExampleModules[`${component}/${example}`]
  if (!entry) return undefined
  return getComponentFromModule(entry)
}

/**
 * Check if an Angular example exists
 */
export function hasAngularExample(component: string, example: string): boolean {
  return `${component}/${example}` in angularExampleModules
}
