// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/src/generate-example-registry.ts
// Run: pnpm --filter scripts generate-example-registry

import * as Collapsible_Basic from '../../../packages/angular/src/collapsible/examples/basic'
import * as Collapsible_Disabled from '../../../packages/angular/src/collapsible/examples/disabled'
import * as Collapsible_Icons from '../../../packages/angular/src/collapsible/examples/icons'
import * as Collapsible_LazyMount from '../../../packages/angular/src/collapsible/examples/lazy-mount'
import * as Collapsible_Nested from '../../../packages/angular/src/collapsible/examples/nested'
import * as Collapsible_PartialCollapse from '../../../packages/angular/src/collapsible/examples/partial-collapse'
import * as Collapsible_RootProvider from '../../../packages/angular/src/collapsible/examples/root-provider'
import * as DateInput_Basic from '../../../packages/angular/src/date-input/examples/basic'
import * as DateInput_Controlled from '../../../packages/angular/src/date-input/examples/controlled'
import * as DateInput_Range from '../../../packages/angular/src/date-input/examples/range'
import * as DateInput_RootProvider from '../../../packages/angular/src/date-input/examples/root-provider'
import * as Dialog_AlertDialog from '../../../packages/angular/src/dialog/examples/alert-dialog'
import * as Dialog_Basic from '../../../packages/angular/src/dialog/examples/basic'
import * as Dialog_Controlled from '../../../packages/angular/src/dialog/examples/controlled'
import * as Dialog_DefaultOpen from '../../../packages/angular/src/dialog/examples/default-open'
import * as Dialog_Icons from '../../../packages/angular/src/dialog/examples/icons'
import * as Dialog_NonModal from '../../../packages/angular/src/dialog/examples/non-modal'
import * as Dialog_RootProvider from '../../../packages/angular/src/dialog/examples/root-provider'
import * as Drawer_Basic from '../../../packages/angular/src/drawer/examples/basic'
import * as Drawer_Controlled from '../../../packages/angular/src/drawer/examples/controlled'
import * as Drawer_DefaultOpen from '../../../packages/angular/src/drawer/examples/default-open'
import * as Drawer_Icons from '../../../packages/angular/src/drawer/examples/icons'
import * as Drawer_RootProvider from '../../../packages/angular/src/drawer/examples/root-provider'
import * as Drawer_SwipeDirection from '../../../packages/angular/src/drawer/examples/swipe-direction'
import * as Drawer_WithTitleDescription from '../../../packages/angular/src/drawer/examples/with-title-description'
import * as HoverCard_Basic from '../../../packages/angular/src/hover-card/examples/basic'
import * as HoverCard_Controlled from '../../../packages/angular/src/hover-card/examples/controlled'
import * as HoverCard_Delay from '../../../packages/angular/src/hover-card/examples/delay'
import * as HoverCard_MultipleTriggers from '../../../packages/angular/src/hover-card/examples/multiple-triggers'
import * as HoverCard_Positioning from '../../../packages/angular/src/hover-card/examples/positioning'
import * as HoverCard_RootProvider from '../../../packages/angular/src/hover-card/examples/root-provider'
import * as ImageCropper_Basic from '../../../packages/angular/src/image-cropper/examples/basic'
import * as ImageCropper_Controlled from '../../../packages/angular/src/image-cropper/examples/controlled'
import * as ImageCropper_RootProvider from '../../../packages/angular/src/image-cropper/examples/root-provider'
import * as JsonTreeView_Basic from '../../../packages/angular/src/json-tree-view/examples/basic'
import * as JsonTreeView_DataTypes from '../../../packages/angular/src/json-tree-view/examples/data-types'
import * as JsonTreeView_RenderValue from '../../../packages/angular/src/json-tree-view/examples/render-value'
import * as JsonTreeView_RootProvider from '../../../packages/angular/src/json-tree-view/examples/root-provider'
import * as Menu_Basic from '../../../packages/angular/src/menu/examples/basic'
import * as Menu_CheckboxItems from '../../../packages/angular/src/menu/examples/checkbox-items'
import * as Menu_ControlledHighlight from '../../../packages/angular/src/menu/examples/controlled-highlight'
import * as Menu_Controlled from '../../../packages/angular/src/menu/examples/controlled'
import * as Menu_Icons from '../../../packages/angular/src/menu/examples/icons'
import * as Menu_ItemGroup from '../../../packages/angular/src/menu/examples/item-group'
import * as Menu_NestedSubmenu from '../../../packages/angular/src/menu/examples/nested-submenu'
import * as Menu_RadioItems from '../../../packages/angular/src/menu/examples/radio-items'
import * as Menu_RootProvider from '../../../packages/angular/src/menu/examples/root-provider'
import * as Menu_WithSeparator from '../../../packages/angular/src/menu/examples/with-separator'
import * as NavigationMenu_Basic from '../../../packages/angular/src/navigation-menu/examples/basic'
import * as NavigationMenu_Controlled from '../../../packages/angular/src/navigation-menu/examples/controlled'
import * as NavigationMenu_Icons from '../../../packages/angular/src/navigation-menu/examples/icons'
import * as NavigationMenu_RootProvider from '../../../packages/angular/src/navigation-menu/examples/root-provider'
import * as NavigationMenu_Viewport from '../../../packages/angular/src/navigation-menu/examples/viewport'
import * as NavigationMenu_WithIndicator from '../../../packages/angular/src/navigation-menu/examples/with-indicator'
import * as Popover_Anchor from '../../../packages/angular/src/popover/examples/anchor'
import * as Popover_Arrow from '../../../packages/angular/src/popover/examples/arrow'
import * as Popover_Basic from '../../../packages/angular/src/popover/examples/basic'
import * as Popover_Controlled from '../../../packages/angular/src/popover/examples/controlled'
import * as Popover_DefaultOpen from '../../../packages/angular/src/popover/examples/default-open'
import * as Popover_Icons from '../../../packages/angular/src/popover/examples/icons'
import * as Popover_Modal from '../../../packages/angular/src/popover/examples/modal'
import * as Popover_RootProvider from '../../../packages/angular/src/popover/examples/root-provider'
import * as QrCode_Basic from '../../../packages/angular/src/qr-code/examples/basic'
import * as QrCode_Controlled from '../../../packages/angular/src/qr-code/examples/controlled'
import * as QrCode_Download from '../../../packages/angular/src/qr-code/examples/download'
import * as QrCode_Overlay from '../../../packages/angular/src/qr-code/examples/overlay'
import * as QrCode_RootProvider from '../../../packages/angular/src/qr-code/examples/root-provider'
import * as SignaturePad_Basic from '../../../packages/angular/src/signature-pad/examples/basic'
import * as SignaturePad_ImagePreview from '../../../packages/angular/src/signature-pad/examples/image-preview'
import * as SignaturePad_RootProvider from '../../../packages/angular/src/signature-pad/examples/root-provider'
import * as Tooltip_Arrow from '../../../packages/angular/src/tooltip/examples/arrow'
import * as Tooltip_Basic from '../../../packages/angular/src/tooltip/examples/basic'
import * as Tooltip_Controlled from '../../../packages/angular/src/tooltip/examples/controlled'
import * as Tooltip_Delay from '../../../packages/angular/src/tooltip/examples/delay'
import * as Tooltip_Interactive from '../../../packages/angular/src/tooltip/examples/interactive'
import * as Tooltip_Positioning from '../../../packages/angular/src/tooltip/examples/positioning'
import * as Tooltip_RootProvider from '../../../packages/angular/src/tooltip/examples/root-provider'
import * as TreeView_AsyncLoading from '../../../packages/angular/src/tree-view/examples/async-loading'
import * as TreeView_Basic from '../../../packages/angular/src/tree-view/examples/basic'
import * as TreeView_CheckboxTree from '../../../packages/angular/src/tree-view/examples/checkbox-tree'
import * as TreeView_ControlledExpanded from '../../../packages/angular/src/tree-view/examples/controlled-expanded'
import * as TreeView_ControlledSelected from '../../../packages/angular/src/tree-view/examples/controlled-selected'
import * as TreeView_ExpandCollapseAll from '../../../packages/angular/src/tree-view/examples/expand-collapse-all'
import * as TreeView_RenameNode from '../../../packages/angular/src/tree-view/examples/rename-node'
import * as TreeView_RootProvider from '../../../packages/angular/src/tree-view/examples/root-provider'

// Registry maps Angular example keys to their module namespace.
type AngularExampleModule = Record<string, unknown>
type AngularExampleEntry = {
  module: AngularExampleModule
  exportName: string
}

const angularExampleModules: Record<string, AngularExampleEntry> = {
  'collapsible/basic': { module: Collapsible_Basic, exportName: 'CollapsibleBasicExample' },
  'collapsible/disabled': { module: Collapsible_Disabled, exportName: 'CollapsibleDisabledExample' },
  'collapsible/icons': { module: Collapsible_Icons, exportName: 'CollapsibleIconsExample' },
  'collapsible/lazy-mount': { module: Collapsible_LazyMount, exportName: 'CollapsibleLazyMountExample' },
  'collapsible/nested': { module: Collapsible_Nested, exportName: 'CollapsibleNestedExample' },
  'collapsible/partial-collapse': {
    module: Collapsible_PartialCollapse,
    exportName: 'CollapsiblePartialCollapseExample',
  },
  'collapsible/root-provider': { module: Collapsible_RootProvider, exportName: 'CollapsibleRootProviderExample' },
  'date-input/basic': { module: DateInput_Basic, exportName: 'DateInputBasicExample' },
  'date-input/controlled': { module: DateInput_Controlled, exportName: 'DateInputControlledExample' },
  'date-input/range': { module: DateInput_Range, exportName: 'DateInputRangeExample' },
  'date-input/root-provider': { module: DateInput_RootProvider, exportName: 'DateInputRootProviderExample' },
  'dialog/alert-dialog': { module: Dialog_AlertDialog, exportName: 'DialogAlertDialogExample' },
  'dialog/basic': { module: Dialog_Basic, exportName: 'DialogBasicExample' },
  'dialog/controlled': { module: Dialog_Controlled, exportName: 'DialogControlledExample' },
  'dialog/default-open': { module: Dialog_DefaultOpen, exportName: 'DialogDefaultOpenExample' },
  'dialog/icons': { module: Dialog_Icons, exportName: 'DialogIconsExample' },
  'dialog/non-modal': { module: Dialog_NonModal, exportName: 'DialogNonModalExample' },
  'dialog/root-provider': { module: Dialog_RootProvider, exportName: 'DialogRootProviderExample' },
  'drawer/basic': { module: Drawer_Basic, exportName: 'DrawerBasicExample' },
  'drawer/controlled': { module: Drawer_Controlled, exportName: 'DrawerControlledExample' },
  'drawer/default-open': { module: Drawer_DefaultOpen, exportName: 'DrawerDefaultOpenExample' },
  'drawer/icons': { module: Drawer_Icons, exportName: 'DrawerIconsExample' },
  'drawer/root-provider': { module: Drawer_RootProvider, exportName: 'DrawerRootProviderExample' },
  'drawer/swipe-direction': { module: Drawer_SwipeDirection, exportName: 'DrawerSwipeDirectionExample' },
  'drawer/with-title-description': {
    module: Drawer_WithTitleDescription,
    exportName: 'DrawerWithTitleDescriptionExample',
  },
  'hover-card/basic': { module: HoverCard_Basic, exportName: 'HoverCardBasicExample' },
  'hover-card/controlled': { module: HoverCard_Controlled, exportName: 'HoverCardControlledExample' },
  'hover-card/delay': { module: HoverCard_Delay, exportName: 'HoverCardDelayExample' },
  'hover-card/multiple-triggers': {
    module: HoverCard_MultipleTriggers,
    exportName: 'HoverCardMultipleTriggersExample',
  },
  'hover-card/positioning': { module: HoverCard_Positioning, exportName: 'HoverCardPositioningExample' },
  'hover-card/root-provider': { module: HoverCard_RootProvider, exportName: 'HoverCardRootProviderExample' },
  'image-cropper/basic': { module: ImageCropper_Basic, exportName: 'ImageCropperBasicExample' },
  'image-cropper/controlled': { module: ImageCropper_Controlled, exportName: 'ImageCropperControlledExample' },
  'image-cropper/root-provider': { module: ImageCropper_RootProvider, exportName: 'ImageCropperRootProviderExample' },
  'json-tree-view/basic': { module: JsonTreeView_Basic, exportName: 'JsonTreeViewBasicExample' },
  'json-tree-view/data-types': { module: JsonTreeView_DataTypes, exportName: 'JsonTreeViewDataTypesExample' },
  'json-tree-view/render-value': { module: JsonTreeView_RenderValue, exportName: 'JsonTreeViewRenderValueExample' },
  'json-tree-view/root-provider': { module: JsonTreeView_RootProvider, exportName: 'JsonTreeViewRootProviderExample' },
  'menu/basic': { module: Menu_Basic, exportName: 'MenuBasicExample' },
  'menu/checkbox-items': { module: Menu_CheckboxItems, exportName: 'MenuCheckboxItemsExample' },
  'menu/controlled-highlight': { module: Menu_ControlledHighlight, exportName: 'MenuControlledHighlightExample' },
  'menu/controlled': { module: Menu_Controlled, exportName: 'MenuControlledExample' },
  'menu/icons': { module: Menu_Icons, exportName: 'MenuIconsExample' },
  'menu/item-group': { module: Menu_ItemGroup, exportName: 'MenuItemGroupExample' },
  'menu/nested-submenu': { module: Menu_NestedSubmenu, exportName: 'MenuNestedSubmenuExample' },
  'menu/radio-items': { module: Menu_RadioItems, exportName: 'MenuRadioItemsExample' },
  'menu/root-provider': { module: Menu_RootProvider, exportName: 'MenuRootProviderExample' },
  'menu/with-separator': { module: Menu_WithSeparator, exportName: 'MenuWithSeparatorExample' },
  'navigation-menu/basic': { module: NavigationMenu_Basic, exportName: 'NavigationMenuBasicExample' },
  'navigation-menu/controlled': { module: NavigationMenu_Controlled, exportName: 'NavigationMenuControlledExample' },
  'navigation-menu/icons': { module: NavigationMenu_Icons, exportName: 'NavigationMenuIconsExample' },
  'navigation-menu/root-provider': {
    module: NavigationMenu_RootProvider,
    exportName: 'NavigationMenuRootProviderExample',
  },
  'navigation-menu/viewport': { module: NavigationMenu_Viewport, exportName: 'NavigationMenuViewportExample' },
  'navigation-menu/with-indicator': {
    module: NavigationMenu_WithIndicator,
    exportName: 'NavigationMenuWithIndicatorExample',
  },
  'popover/anchor': { module: Popover_Anchor, exportName: 'PopoverAnchorExample' },
  'popover/arrow': { module: Popover_Arrow, exportName: 'PopoverArrowExample' },
  'popover/basic': { module: Popover_Basic, exportName: 'PopoverBasicExample' },
  'popover/controlled': { module: Popover_Controlled, exportName: 'PopoverControlledExample' },
  'popover/default-open': { module: Popover_DefaultOpen, exportName: 'PopoverDefaultOpenExample' },
  'popover/icons': { module: Popover_Icons, exportName: 'PopoverIconsExample' },
  'popover/modal': { module: Popover_Modal, exportName: 'PopoverModalExample' },
  'popover/root-provider': { module: Popover_RootProvider, exportName: 'PopoverRootProviderExample' },
  'qr-code/basic': { module: QrCode_Basic, exportName: 'QrCodeBasicExample' },
  'qr-code/controlled': { module: QrCode_Controlled, exportName: 'QrCodeControlledExample' },
  'qr-code/download': { module: QrCode_Download, exportName: 'QrCodeDownloadExample' },
  'qr-code/overlay': { module: QrCode_Overlay, exportName: 'QrCodeOverlayExample' },
  'qr-code/root-provider': { module: QrCode_RootProvider, exportName: 'QrCodeRootProviderExample' },
  'signature-pad/basic': { module: SignaturePad_Basic, exportName: 'SignaturePadBasicExample' },
  'signature-pad/image-preview': { module: SignaturePad_ImagePreview, exportName: 'SignaturePadImagePreviewExample' },
  'signature-pad/root-provider': { module: SignaturePad_RootProvider, exportName: 'SignaturePadRootProviderExample' },
  'tooltip/arrow': { module: Tooltip_Arrow, exportName: 'TooltipArrowExample' },
  'tooltip/basic': { module: Tooltip_Basic, exportName: 'TooltipBasicExample' },
  'tooltip/controlled': { module: Tooltip_Controlled, exportName: 'TooltipControlledExample' },
  'tooltip/delay': { module: Tooltip_Delay, exportName: 'TooltipDelayExample' },
  'tooltip/interactive': { module: Tooltip_Interactive, exportName: 'TooltipInteractiveExample' },
  'tooltip/positioning': { module: Tooltip_Positioning, exportName: 'TooltipPositioningExample' },
  'tooltip/root-provider': { module: Tooltip_RootProvider, exportName: 'TooltipRootProviderExample' },
  'tree-view/async-loading': { module: TreeView_AsyncLoading, exportName: 'TreeViewAsyncLoadingExample' },
  'tree-view/basic': { module: TreeView_Basic, exportName: 'TreeViewBasicExample' },
  'tree-view/checkbox-tree': { module: TreeView_CheckboxTree, exportName: 'TreeViewCheckboxTreeExample' },
  'tree-view/controlled-expanded': {
    module: TreeView_ControlledExpanded,
    exportName: 'TreeViewControlledExpandedExample',
  },
  'tree-view/controlled-selected': {
    module: TreeView_ControlledSelected,
    exportName: 'TreeViewControlledSelectedExample',
  },
  'tree-view/expand-collapse-all': {
    module: TreeView_ExpandCollapseAll,
    exportName: 'TreeViewExpandCollapseAllExample',
  },
  'tree-view/rename-node': { module: TreeView_RenameNode, exportName: 'TreeViewRenameNodeExample' },
  'tree-view/root-provider': { module: TreeView_RootProvider, exportName: 'TreeViewRootProviderExample' },
}

/**
 * Get the Angular component export from a module
 */
function getComponentFromModule(entry: AngularExampleEntry): unknown {
  const value = entry.module[entry.exportName]
  return typeof value === 'function' ? value : undefined
}

/**
 * Get an Angular example component by component name and example id
 */
export function getAngularExample(component: string, example: string): unknown {
  const entry = angularExampleModules[`${component}/${example}`]
  if (!entry) return undefined
  return getComponentFromModule(entry)
}

/**
 * Check if an Angular example exists
 */
export function hasAngularExample(component: string, example: string): boolean {
  return `${component}/${example}` in angularExampleModules
}
