// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/src/generate-example-registry.ts
// Run: pnpm --filter scripts generate-example-registry

import type { ComponentType } from 'react'

import * as Accordion_Basic from '@examples/accordion/examples/basic'
import * as Accordion_Collapsible from '@examples/accordion/examples/collapsible'
import * as Accordion_Context from '@examples/accordion/examples/context'
import * as Accordion_Controlled from '@examples/accordion/examples/controlled'
import * as Accordion_Disabled from '@examples/accordion/examples/disabled'
import * as Accordion_Horizontal from '@examples/accordion/examples/horizontal'
import * as Accordion_ItemContext from '@examples/accordion/examples/item-context'
import * as Accordion_LazyMount from '@examples/accordion/examples/lazy-mount'
import * as Accordion_Multiple from '@examples/accordion/examples/multiple'
import * as Accordion_RootProvider from '@examples/accordion/examples/root-provider'
import * as Accordion_WithSlider from '@examples/accordion/examples/with-slider'
import * as AngleSlider_Basic from '@examples/angle-slider/examples/basic'
import * as AngleSlider_Context from '@examples/angle-slider/examples/context'
import * as AngleSlider_Controlled from '@examples/angle-slider/examples/controlled'
import * as AngleSlider_Disabled from '@examples/angle-slider/examples/disabled'
import * as AngleSlider_RootProvider from '@examples/angle-slider/examples/root-provider'
import * as AngleSlider_Step from '@examples/angle-slider/examples/step'
import * as Avatar_Basic from '@examples/avatar/examples/basic'
import * as Avatar_Context from '@examples/avatar/examples/context'
import * as Avatar_Events from '@examples/avatar/examples/events'
import * as Avatar_Provider from '@examples/avatar/examples/provider'
import * as Avatar_RootProvider from '@examples/avatar/examples/root-provider'
import * as BottomSheet_Basic from '@examples/bottom-sheet/examples/basic'
import * as BottomSheet_Controlled from '@examples/bottom-sheet/examples/controlled'
import * as BottomSheet_Modal from '@examples/bottom-sheet/examples/modal'
import * as BottomSheet_NoDragArea from '@examples/bottom-sheet/examples/no-drag-area'
import * as BottomSheet_NonDraggable from '@examples/bottom-sheet/examples/non-draggable'
import * as BottomSheet_RootProvider from '@examples/bottom-sheet/examples/root-provider'
import * as BottomSheet_Scrollable from '@examples/bottom-sheet/examples/scrollable'
import * as BottomSheet_SnapPoints from '@examples/bottom-sheet/examples/snap-points'
import * as Carousel_Autoplay from '@examples/carousel/examples/autoplay'
import * as Carousel_Basic from '@examples/carousel/examples/basic'
import * as Carousel_Controlled from '@examples/carousel/examples/controlled'
import * as Carousel_DynamicSlides from '@examples/carousel/examples/dynamic-slides'
import * as Carousel_PauseOnHover from '@examples/carousel/examples/pause-on-hover'
import * as Carousel_RootProvider from '@examples/carousel/examples/root-provider'
import * as Carousel_ScrollTo from '@examples/carousel/examples/scroll-to'
import * as Carousel_SlidesPerPage from '@examples/carousel/examples/slides-per-page'
import * as Carousel_Spacing from '@examples/carousel/examples/spacing'
import * as Carousel_ThumbnailIndicator from '@examples/carousel/examples/thumbnail-indicator'
import * as Carousel_VariableSize from '@examples/carousel/examples/variable-size'
import * as Carousel_Vertical from '@examples/carousel/examples/vertical'
import * as Checkbox_Basic from '@examples/checkbox/examples/basic'
import * as Checkbox_Context from '@examples/checkbox/examples/context'
import * as Checkbox_Controlled from '@examples/checkbox/examples/controlled'
import * as Checkbox_DefaultChecked from '@examples/checkbox/examples/default-checked'
import * as Checkbox_Disabled from '@examples/checkbox/examples/disabled'
import * as Checkbox_GroupControlled from '@examples/checkbox/examples/group-controlled'
import * as Checkbox_GroupProvider from '@examples/checkbox/examples/group-provider'
import * as Checkbox_GroupWithFieldset from '@examples/checkbox/examples/group-with-fieldset'
import * as Checkbox_GroupWithForm from '@examples/checkbox/examples/group-with-form'
import * as Checkbox_GroupWithInvalid from '@examples/checkbox/examples/group-with-invalid'
import * as Checkbox_GroupWithSelectAll from '@examples/checkbox/examples/group-with-select-all'
import * as Checkbox_Group from '@examples/checkbox/examples/group'
import * as Checkbox_Indeterminate from '@examples/checkbox/examples/indeterminate'
import * as Checkbox_RootProvider from '@examples/checkbox/examples/root-provider'
import * as Checkbox_WithField from '@examples/checkbox/examples/with-field'
import * as Checkbox_WithForm from '@examples/checkbox/examples/with-form'
import * as ClientOnly_Basic from '@examples/client-only/examples/basic'
import * as ClientOnly_WithFallback from '@examples/client-only/examples/with-fallback'
import * as Clipboard_Basic from '@examples/clipboard/examples/basic'
import * as Clipboard_Context from '@examples/clipboard/examples/context'
import * as Clipboard_Controlled from '@examples/clipboard/examples/controlled'
import * as Clipboard_CopyStatus from '@examples/clipboard/examples/copy-status'
import * as Clipboard_RootProvider from '@examples/clipboard/examples/root-provider'
import * as Clipboard_Timeout from '@examples/clipboard/examples/timeout'
import * as Clipboard_ValueText from '@examples/clipboard/examples/value-text'
import * as Collapsible_Basic from '@examples/collapsible/examples/basic'
import * as Collapsible_Disabled from '@examples/collapsible/examples/disabled'
import * as Collapsible_InitialOpen from '@examples/collapsible/examples/initial-open'
import * as Collapsible_LazyMount from '@examples/collapsible/examples/lazy-mount'
import * as Collapsible_Nested from '@examples/collapsible/examples/nested'
import * as Collapsible_PartialCollapse from '@examples/collapsible/examples/partial-collapse'
import * as Collapsible_RootProvider from '@examples/collapsible/examples/root-provider'
import * as CollectionAsyncList_Dependencies from '@examples/collection/examples/async-list/dependencies'
import * as CollectionAsyncList_Filter from '@examples/collection/examples/async-list/filter'
import * as CollectionAsyncList_InfiniteLoading from '@examples/collection/examples/async-list/infinite-loading'
import * as CollectionAsyncList_Reload from '@examples/collection/examples/async-list/reload'
import * as CollectionAsyncList_SortClientSide from '@examples/collection/examples/async-list/sort-client-side'
import * as CollectionAsyncList_SortServerSide from '@examples/collection/examples/async-list/sort-server-side'
import * as CollectionListSelection_Basic from '@examples/collection/examples/list-selection/basic'
import * as CollectionListSelection_Multiple from '@examples/collection/examples/list-selection/multiple'
import * as CollectionListSelection_Range from '@examples/collection/examples/list-selection/range'
import * as ColorPicker_Basic from '@examples/color-picker/examples/basic'
import * as ColorPicker_Controlled from '@examples/color-picker/examples/controlled'
import * as ColorPicker_Disabled from '@examples/color-picker/examples/disabled'
import * as ColorPicker_FormUsage from '@examples/color-picker/examples/form-usage'
import * as ColorPicker_Inline from '@examples/color-picker/examples/inline'
import * as ColorPicker_InputOnly from '@examples/color-picker/examples/input-only'
import * as ColorPicker_OpenControlled from '@examples/color-picker/examples/open-controlled'
import * as ColorPicker_RootProvider from '@examples/color-picker/examples/root-provider'
import * as ColorPicker_SliderOnly from '@examples/color-picker/examples/slider-only'
import * as ColorPicker_SwatchOnly from '@examples/color-picker/examples/swatch-only'
import * as ColorPicker_Swatches from '@examples/color-picker/examples/swatches'
import * as ColorPicker_ValueSwatch from '@examples/color-picker/examples/value-swatch'
import * as ColorPicker_WithField from '@examples/color-picker/examples/with-field'
import * as Combobox_AsyncSearch from '@examples/combobox/examples/async-search'
import * as Combobox_AutoHighlight from '@examples/combobox/examples/auto-highlight'
import * as Combobox_Basic from '@examples/combobox/examples/basic'
import * as Combobox_Context from '@examples/combobox/examples/context'
import * as Combobox_Creatable from '@examples/combobox/examples/creatable'
import * as Combobox_CustomObject from '@examples/combobox/examples/custom-object'
import * as Combobox_Dynamic from '@examples/combobox/examples/dynamic'
import * as Combobox_Grouping from '@examples/combobox/examples/grouping'
import * as Combobox_HighlightMatchingText from '@examples/combobox/examples/highlight-matching-text'
import * as Combobox_InlineAutocomplete from '@examples/combobox/examples/inline-autocomplete'
import * as Combobox_LimitResults from '@examples/combobox/examples/limit-results'
import * as Combobox_Links from '@examples/combobox/examples/links'
import * as Combobox_Multiple from '@examples/combobox/examples/multiple'
import * as Combobox_RehydrateValue from '@examples/combobox/examples/rehydrate-value'
import * as Combobox_RootProvider from '@examples/combobox/examples/root-provider'
import * as Combobox_Virtualized from '@examples/combobox/examples/virtualized'
import * as Combobox_WithField from '@examples/combobox/examples/with-field'
import * as DatePicker_Basic from '@examples/date-picker/examples/basic'
import * as DatePicker_Controlled from '@examples/date-picker/examples/controlled'
import * as DatePicker_DefaultValue from '@examples/date-picker/examples/default-value'
import * as DatePicker_DefaultView from '@examples/date-picker/examples/default-view'
import * as DatePicker_FormatParse from '@examples/date-picker/examples/format-parse'
import * as DatePicker_Inline from '@examples/date-picker/examples/inline'
import * as DatePicker_Locale from '@examples/date-picker/examples/locale'
import * as DatePicker_MinMax from '@examples/date-picker/examples/min-max'
import * as DatePicker_MonthPicker from '@examples/date-picker/examples/month-picker'
import * as DatePicker_MonthRange from '@examples/date-picker/examples/month-range'
import * as DatePicker_MultiSelection from '@examples/date-picker/examples/multi-selection'
import * as DatePicker_MultipleMonths from '@examples/date-picker/examples/multiple-months'
import * as DatePicker_Presets from '@examples/date-picker/examples/presets'
import * as DatePicker_RangeSelection from '@examples/date-picker/examples/range-selection'
import * as DatePicker_RootProvider from '@examples/date-picker/examples/root-provider'
import * as DatePicker_Unavailable from '@examples/date-picker/examples/unavailable'
import * as DatePicker_YearPickerRange from '@examples/date-picker/examples/year-picker-range'
import * as DatePicker_YearPicker from '@examples/date-picker/examples/year-picker'
import * as Dialog_AlertDialog from '@examples/dialog/examples/alert-dialog'
import * as Dialog_Basic from '@examples/dialog/examples/basic'
import * as Dialog_CloseOnEscape from '@examples/dialog/examples/close-on-escape'
import * as Dialog_CloseOnInteractOutside from '@examples/dialog/examples/close-on-interact-outside'
import * as Dialog_Confirmation from '@examples/dialog/examples/confirmation'
import * as Dialog_Context from '@examples/dialog/examples/context'
import * as Dialog_Controlled from '@examples/dialog/examples/controlled'
import * as Dialog_FinalFocus from '@examples/dialog/examples/final-focus'
import * as Dialog_InitialFocus from '@examples/dialog/examples/initial-focus'
import * as Dialog_LazyMount from '@examples/dialog/examples/lazy-mount'
import * as Dialog_Nested from '@examples/dialog/examples/nested'
import * as Dialog_NonModal from '@examples/dialog/examples/non-modal'
import * as Dialog_RapidStateChange from '@examples/dialog/examples/rapid-state-change'
import * as Dialog_RootProvider from '@examples/dialog/examples/root-provider'
import * as DownloadTrigger_Basic from '@examples/download-trigger/examples/basic'
import * as DownloadTrigger_Svg from '@examples/download-trigger/examples/svg'
import * as DownloadTrigger_WithPromise from '@examples/download-trigger/examples/with-promise'
import * as Editable_Basic from '@examples/editable/examples/basic'
import * as Editable_Context from '@examples/editable/examples/context'
import * as Editable_Controlled from '@examples/editable/examples/controlled'
import * as Editable_Controls from '@examples/editable/examples/controls'
import * as Editable_DoubleClick from '@examples/editable/examples/double-click'
import * as Editable_RootProvider from '@examples/editable/examples/root-provider'
import * as Editable_Textarea from '@examples/editable/examples/textarea'
import * as Editable_WithField from '@examples/editable/examples/with-field'
import * as Field_CustomControl from '@examples/field/examples/custom-control'
import * as Field_Disabled from '@examples/field/examples/disabled'
import * as Field_Input from '@examples/field/examples/input'
import * as Field_Invalid from '@examples/field/examples/invalid'
import * as Field_RequiredIndicator from '@examples/field/examples/required-indicator'
import * as Field_RootProvider from '@examples/field/examples/root-provider'
import * as Field_Select from '@examples/field/examples/select'
import * as Field_ShadowDom from '@examples/field/examples/shadow-dom'
import * as Field_TextareaAutoresize from '@examples/field/examples/textarea-autoresize'
import * as Field_Textarea from '@examples/field/examples/textarea'
import * as Fieldset_Basic from '@examples/fieldset/examples/basic'
import * as Fieldset_Disabled from '@examples/fieldset/examples/disabled'
import * as Fieldset_Invalid from '@examples/fieldset/examples/invalid'
import * as Fieldset_PhoneInput from '@examples/fieldset/examples/phone-input'
import * as Fieldset_RootProvider from '@examples/fieldset/examples/root-provider'
import * as Fieldset_WithCheckbox from '@examples/fieldset/examples/with-checkbox'
import * as Fieldset_WithField from '@examples/fieldset/examples/with-field'
import * as FileUpload_AcceptedFileTypes from '@examples/file-upload/examples/accepted-file-types'
import * as FileUpload_Basic from '@examples/file-upload/examples/basic'
import * as FileUpload_ClearTrigger from '@examples/file-upload/examples/clear-trigger'
import * as FileUpload_DirectoryUpload from '@examples/file-upload/examples/directory-upload'
import * as FileUpload_Dropzone from '@examples/file-upload/examples/dropzone'
import * as FileUpload_ErrorHandling from '@examples/file-upload/examples/error-handling'
import * as FileUpload_FormUsage from '@examples/file-upload/examples/form-usage'
import * as FileUpload_InitialFiles from '@examples/file-upload/examples/initial-files'
import * as FileUpload_MediaCapture from '@examples/file-upload/examples/media-capture'
import * as FileUpload_PastingFiles from '@examples/file-upload/examples/pasting-files'
import * as FileUpload_RejectedFiles from '@examples/file-upload/examples/rejected-files'
import * as FileUpload_RootProvider from '@examples/file-upload/examples/root-provider'
import * as FileUpload_TransformFiles from '@examples/file-upload/examples/transform-files'
import * as FileUpload_WithField from '@examples/file-upload/examples/with-field'
import * as FloatingPanel_AnchorPosition from '@examples/floating-panel/examples/anchor-position'
import * as FloatingPanel_Basic from '@examples/floating-panel/examples/basic'
import * as FloatingPanel_Context from '@examples/floating-panel/examples/context'
import * as FloatingPanel_ControlledOpen from '@examples/floating-panel/examples/controlled-open'
import * as FloatingPanel_ControlledPosition from '@examples/floating-panel/examples/controlled-position'
import * as FloatingPanel_ControlledSize from '@examples/floating-panel/examples/controlled-size'
import * as FloatingPanel_LazyMount from '@examples/floating-panel/examples/lazy-mount'
import * as FocusTrap_Autofocus from '@examples/focus-trap/examples/autofocus'
import * as FocusTrap_Basic from '@examples/focus-trap/examples/basic'
import * as FocusTrap_InitialFocus from '@examples/focus-trap/examples/initial-focus'
import * as Format_ByteBasic from '@examples/format/examples/byte-basic'
import * as Format_ByteSizes from '@examples/format/examples/byte-sizes'
import * as Format_ByteWithLocale from '@examples/format/examples/byte-with-locale'
import * as Format_ByteWithUnitDisplay from '@examples/format/examples/byte-with-unit-display'
import * as Format_ByteWithUnitSystem from '@examples/format/examples/byte-with-unit-system'
import * as Format_ByteWithUnit from '@examples/format/examples/byte-with-unit'
import * as Format_NumberBasic from '@examples/format/examples/number-basic'
import * as Format_NumberWithCompact from '@examples/format/examples/number-with-compact'
import * as Format_NumberWithCurrency from '@examples/format/examples/number-with-currency'
import * as Format_NumberWithLocale from '@examples/format/examples/number-with-locale'
import * as Format_NumberWithPercentage from '@examples/format/examples/number-with-percentage'
import * as Format_NumberWithUnit from '@examples/format/examples/number-with-unit'
import * as Format_RelativeTimeBasic from '@examples/format/examples/relative-time-basic'
import * as Format_RelativeTimeShort from '@examples/format/examples/relative-time-short'
import * as Frame_Basic from '@examples/frame/examples/basic'
import * as Frame_InheritStyles from '@examples/frame/examples/inherit-styles'
import * as Frame_Script from '@examples/frame/examples/script'
import * as Frame_SrcDoc from '@examples/frame/examples/src-doc'
import * as Highlight_Basic from '@examples/highlight/examples/basic'
import * as Highlight_DynamicQuery from '@examples/highlight/examples/dynamic-query'
import * as Highlight_ExactMatch from '@examples/highlight/examples/exact-match'
import * as Highlight_IgnoreCase from '@examples/highlight/examples/ignore-case'
import * as Highlight_MatchAll from '@examples/highlight/examples/match-all'
import * as Highlight_Multiple from '@examples/highlight/examples/multiple'
import * as Highlight_RepeatingText from '@examples/highlight/examples/repeating-text'
import * as HoverCard_Basic from '@examples/hover-card/examples/basic'
import * as HoverCard_Context from '@examples/hover-card/examples/context'
import * as HoverCard_Controlled from '@examples/hover-card/examples/controlled'
import * as HoverCard_Delay from '@examples/hover-card/examples/delay'
import * as HoverCard_Positioning from '@examples/hover-card/examples/positioning'
import * as HoverCard_RootProvider from '@examples/hover-card/examples/root-provider'
import * as ImageCropper_AspectRatio from '@examples/image-cropper/examples/aspect-ratio'
import * as ImageCropper_Basic from '@examples/image-cropper/examples/basic'
import * as ImageCropper_Circle from '@examples/image-cropper/examples/circle'
import * as ImageCropper_Context from '@examples/image-cropper/examples/context'
import * as ImageCropper_ControlledZoom from '@examples/image-cropper/examples/controlled-zoom'
import * as ImageCropper_CropPreview from '@examples/image-cropper/examples/crop-preview'
import * as ImageCropper_Events from '@examples/image-cropper/examples/events'
import * as ImageCropper_Fixed from '@examples/image-cropper/examples/fixed'
import * as ImageCropper_Flip from '@examples/image-cropper/examples/flip'
import * as ImageCropper_InitialCrop from '@examples/image-cropper/examples/initial-crop'
import * as ImageCropper_MinMaxSize from '@examples/image-cropper/examples/min-max-size'
import * as ImageCropper_Reset from '@examples/image-cropper/examples/reset'
import * as ImageCropper_RootProvider from '@examples/image-cropper/examples/root-provider'
import * as ImageCropper_Rotation from '@examples/image-cropper/examples/rotation'
import * as ImageCropper_ZoomLimits from '@examples/image-cropper/examples/zoom-limits'
import * as JsonTreeView_ArrayData from '@examples/json-tree-view/examples/array-data'
import * as JsonTreeView_Basic from '@examples/json-tree-view/examples/basic'
import * as JsonTreeView_Errors from '@examples/json-tree-view/examples/errors'
import * as JsonTreeView_ExpandLevel from '@examples/json-tree-view/examples/expand-level'
import * as JsonTreeView_Functions from '@examples/json-tree-view/examples/functions'
import * as JsonTreeView_MapAndSet from '@examples/json-tree-view/examples/map-and-set'
import * as JsonTreeView_Regex from '@examples/json-tree-view/examples/regex'
import * as JsonTreeView_RenderValue from '@examples/json-tree-view/examples/render-value'
import * as JsonTreeView_RootProvider from '@examples/json-tree-view/examples/root-provider'
import * as Listbox_Basic from '@examples/listbox/examples/basic'
import * as Listbox_Controlled from '@examples/listbox/examples/controlled'
import * as Listbox_DisabledItem from '@examples/listbox/examples/disabled-item'
import * as Listbox_ExtendedSelect from '@examples/listbox/examples/extended-select'
import * as Listbox_Filtering from '@examples/listbox/examples/filtering'
import * as Listbox_Grid from '@examples/listbox/examples/grid'
import * as Listbox_Group from '@examples/listbox/examples/group'
import * as Listbox_Horizontal from '@examples/listbox/examples/horizontal'
import * as Listbox_Multiple from '@examples/listbox/examples/multiple'
import * as Listbox_RootProvider from '@examples/listbox/examples/root-provider'
import * as Listbox_SelectAll from '@examples/listbox/examples/select-all'
import * as Listbox_ValueText from '@examples/listbox/examples/value-text'
import * as Marquee_AutoFill from '@examples/marquee/examples/auto-fill'
import * as Marquee_Basic from '@examples/marquee/examples/basic'
import * as Marquee_FiniteLoops from '@examples/marquee/examples/finite-loops'
import * as Marquee_PauseOnInteraction from '@examples/marquee/examples/pause-on-interaction'
import * as Marquee_ProgrammaticControl from '@examples/marquee/examples/programmatic-control'
import * as Marquee_Reverse from '@examples/marquee/examples/reverse'
import * as Marquee_Speed from '@examples/marquee/examples/speed'
import * as Marquee_Vertical from '@examples/marquee/examples/vertical'
import * as Marquee_WithEdges from '@examples/marquee/examples/with-edges'
import * as Menu_Basic from '@examples/menu/examples/basic'
import * as Menu_CheckboxItems from '@examples/menu/examples/checkbox-items'
import * as Menu_ContextLazyMount from '@examples/menu/examples/context-lazy-mount'
import * as Menu_Context from '@examples/menu/examples/context'
import * as Menu_Controlled from '@examples/menu/examples/controlled'
import * as Menu_Group from '@examples/menu/examples/group'
import * as Menu_ItemContext from '@examples/menu/examples/item-context'
import * as Menu_Links from '@examples/menu/examples/links'
import * as Menu_MenuInDialog from '@examples/menu/examples/menu-in-dialog'
import * as Menu_MenuItemDialog from '@examples/menu/examples/menu-item-dialog'
import * as Menu_MultipleMenu from '@examples/menu/examples/multiple-menu'
import * as Menu_Nested from '@examples/menu/examples/nested'
import * as Menu_RadioItems from '@examples/menu/examples/radio-items'
import * as Menu_RootProvider from '@examples/menu/examples/root-provider'
import * as Menu_SelectEvent from '@examples/menu/examples/select-event'
import * as NavigationMenu_Basic from '@examples/navigation-menu/examples/basic'
import * as NavigationMenu_Context from '@examples/navigation-menu/examples/context'
import * as NavigationMenu_Controlled from '@examples/navigation-menu/examples/controlled'
import * as NavigationMenu_RootProvider from '@examples/navigation-menu/examples/root-provider'
import * as NavigationMenu_Viewport from '@examples/navigation-menu/examples/viewport'
import * as NumberInput_Basic from '@examples/number-input/examples/basic'
import * as NumberInput_Context from '@examples/number-input/examples/context'
import * as NumberInput_Formatting from '@examples/number-input/examples/formatting'
import * as NumberInput_FractionDigits from '@examples/number-input/examples/fraction-digits'
import * as NumberInput_MinMax from '@examples/number-input/examples/min-max'
import * as NumberInput_MouseWheel from '@examples/number-input/examples/mouse-wheel'
import * as NumberInput_RootProvider from '@examples/number-input/examples/root-provider'
import * as NumberInput_Scrubber from '@examples/number-input/examples/scrubber'
import * as NumberInput_WithField from '@examples/number-input/examples/with-field'
import * as Pagination_Basic from '@examples/pagination/examples/basic'
import * as Pagination_Context from '@examples/pagination/examples/context'
import * as Pagination_Controlled from '@examples/pagination/examples/controlled'
import * as Pagination_Customized from '@examples/pagination/examples/customized'
import * as Pagination_DataSlicing from '@examples/pagination/examples/data-slicing'
import * as Pagination_Link from '@examples/pagination/examples/link'
import * as Pagination_PageRange from '@examples/pagination/examples/page-range'
import * as Pagination_PageSizeControl from '@examples/pagination/examples/page-size-control'
import * as Pagination_RootProvider from '@examples/pagination/examples/root-provider'
import * as Pagination_WithEdges from '@examples/pagination/examples/with-edges'
import * as PasswordInput_Autocomplete from '@examples/password-input/examples/autocomplete'
import * as PasswordInput_Basic from '@examples/password-input/examples/basic'
import * as PasswordInput_ControlledVisibility from '@examples/password-input/examples/controlled-visibility'
import * as PasswordInput_IgnorePasswordManager from '@examples/password-input/examples/ignore-password-manager'
import * as PasswordInput_RootProvider from '@examples/password-input/examples/root-provider'
import * as PasswordInput_StrengthMeter from '@examples/password-input/examples/strength-meter'
import * as PasswordInput_WithField from '@examples/password-input/examples/with-field'
import * as PasswordInput_WithValidation from '@examples/password-input/examples/with-validation'
import * as PinInput_Basic from '@examples/pin-input/examples/basic'
import * as PinInput_BlurOnComplete from '@examples/pin-input/examples/blur-on-complete'
import * as PinInput_CustomPlaceholder from '@examples/pin-input/examples/custom-placeholder'
import * as PinInput_Mask from '@examples/pin-input/examples/mask'
import * as PinInput_OtpMode from '@examples/pin-input/examples/otp-mode'
import * as PinInput_RootProvider from '@examples/pin-input/examples/root-provider'
import * as PinInput_WithField from '@examples/pin-input/examples/with-field'
import * as Popover_Anchor from '@examples/popover/examples/anchor'
import * as Popover_Arrow from '@examples/popover/examples/arrow'
import * as Popover_AsChild from '@examples/popover/examples/as-child'
import * as Popover_Basic from '@examples/popover/examples/basic'
import * as Popover_CloseBehavior from '@examples/popover/examples/close-behavior'
import * as Popover_Context from '@examples/popover/examples/context'
import * as Popover_Controlled from '@examples/popover/examples/controlled'
import * as Popover_DisableOutsideClick from '@examples/popover/examples/disable-outside-click'
import * as Popover_Factory from '@examples/popover/examples/factory'
import * as Popover_InitialFocus from '@examples/popover/examples/initial-focus'
import * as Popover_LazyMount from '@examples/popover/examples/lazy-mount'
import * as Popover_Modal from '@examples/popover/examples/modal'
import * as Popover_Nested from '@examples/popover/examples/nested'
import * as Popover_Positioning from '@examples/popover/examples/positioning'
import * as Popover_RootProvider from '@examples/popover/examples/root-provider'
import * as Popover_SameWidth from '@examples/popover/examples/same-width'
import * as Popover_WithDialog from '@examples/popover/examples/with-dialog'
import * as Presence_Basic from '@examples/presence/examples/basic'
import * as Presence_LazyMountAndUnmountOnExit from '@examples/presence/examples/lazy-mount-and-unmount-on-exit'
import * as Presence_LazyMount from '@examples/presence/examples/lazy-mount'
import * as Presence_SkipAnimationOnMount from '@examples/presence/examples/skip-animation-on-mount'
import * as Presence_UnmountOnExit from '@examples/presence/examples/unmount-on-exit'
import * as ProgressCircular_Basic from '@examples/progress/examples/circular/basic'
import * as ProgressCircular_Controlled from '@examples/progress/examples/circular/controlled'
import * as ProgressCircular_Indeterminate from '@examples/progress/examples/circular/indeterminate'
import * as ProgressCircular_InitialValue from '@examples/progress/examples/circular/initial-value'
import * as ProgressCircular_MinMax from '@examples/progress/examples/circular/min-max'
import * as ProgressCircular_RootProvider from '@examples/progress/examples/circular/root-provider'
import * as ProgressCircular_WithLabel from '@examples/progress/examples/circular/with-label'
import * as ProgressLinear_Basic from '@examples/progress/examples/linear/basic'
import * as ProgressLinear_Controlled from '@examples/progress/examples/linear/controlled'
import * as ProgressLinear_Indeterminate from '@examples/progress/examples/linear/indeterminate'
import * as ProgressLinear_InitialValue from '@examples/progress/examples/linear/initial-value'
import * as ProgressLinear_MinMax from '@examples/progress/examples/linear/min-max'
import * as ProgressLinear_RootProvider from '@examples/progress/examples/linear/root-provider'
import * as ProgressLinear_ValueText from '@examples/progress/examples/linear/value-text'
import * as ProgressLinear_Vertical from '@examples/progress/examples/linear/vertical'
import * as QrCode_Basic from '@examples/qr-code/examples/basic'
import * as QrCode_Controlled from '@examples/qr-code/examples/controlled'
import * as QrCode_Download from '@examples/qr-code/examples/download'
import * as QrCode_ErrorCorrection from '@examples/qr-code/examples/error-correction'
import * as QrCode_Fill from '@examples/qr-code/examples/fill'
import * as QrCode_Overlay from '@examples/qr-code/examples/overlay'
import * as QrCode_RootProvider from '@examples/qr-code/examples/root-provider'
import * as RadioGroup_Basic from '@examples/radio-group/examples/basic'
import * as RadioGroup_Controlled from '@examples/radio-group/examples/controlled'
import * as RadioGroup_Disabled from '@examples/radio-group/examples/disabled'
import * as RadioGroup_InitialValue from '@examples/radio-group/examples/initial-value'
import * as RadioGroup_Orientation from '@examples/radio-group/examples/orientation'
import * as RadioGroup_RootProvider from '@examples/radio-group/examples/root-provider'
import * as RadioGroup_WithFieldset from '@examples/radio-group/examples/with-fieldset'
import * as RatingGroup_Basic from '@examples/rating-group/examples/basic'
import * as RatingGroup_Controlled from '@examples/rating-group/examples/controlled'
import * as RatingGroup_Disabled from '@examples/rating-group/examples/disabled'
import * as RatingGroup_FormUsage from '@examples/rating-group/examples/form-usage'
import * as RatingGroup_HalfStar from '@examples/rating-group/examples/half-star'
import * as RatingGroup_RootProvider from '@examples/rating-group/examples/root-provider'
import * as RatingGroup_WithField from '@examples/rating-group/examples/with-field'
import * as ScrollArea_Basic from '@examples/scroll-area/examples/basic'
import * as ScrollArea_BothDirections from '@examples/scroll-area/examples/both-directions'
import * as ScrollArea_Horizontal from '@examples/scroll-area/examples/horizontal'
import * as ScrollArea_Nested from '@examples/scroll-area/examples/nested'
import * as ScrollArea_RootProvider from '@examples/scroll-area/examples/root-provider'
import * as SegmentGroup_Basic from '@examples/segment-group/examples/basic'
import * as SegmentGroup_Conditional from '@examples/segment-group/examples/conditional'
import * as SegmentGroup_Controlled from '@examples/segment-group/examples/controlled'
import * as SegmentGroup_Disabled from '@examples/segment-group/examples/disabled'
import * as SegmentGroup_RootProvider from '@examples/segment-group/examples/root-provider'
import * as Select_Async from '@examples/select/examples/async'
import * as Select_Basic from '@examples/select/examples/basic'
import * as Select_Controlled from '@examples/select/examples/controlled'
import * as Select_DynamicItems from '@examples/select/examples/dynamic-items'
import * as Select_FormLibrary from '@examples/select/examples/form-library'
import * as Select_FullyControlled from '@examples/select/examples/fully-controlled'
import * as Select_Grouping from '@examples/select/examples/grouping'
import * as Select_LazyMount from '@examples/select/examples/lazy-mount'
import * as Select_MaxSelected from '@examples/select/examples/max-selected'
import * as Select_Multiple from '@examples/select/examples/multiple'
import * as Select_Overflow from '@examples/select/examples/overflow'
import * as Select_ReactiveCollection from '@examples/select/examples/reactive-collection'
import * as Select_RootProvider from '@examples/select/examples/root-provider'
import * as Select_SelectAll from '@examples/select/examples/select-all'
import * as Select_SelectOnHighlight from '@examples/select/examples/select-on-highlight'
import * as Select_WithField from '@examples/select/examples/with-field'
import * as SignaturePad_Basic from '@examples/signature-pad/examples/basic'
import * as SignaturePad_ImagePreview from '@examples/signature-pad/examples/image-preview'
import * as SignaturePad_RootProvider from '@examples/signature-pad/examples/root-provider'
import * as SignaturePad_WithField from '@examples/signature-pad/examples/with-field'
import * as Slider_Basic from '@examples/slider/examples/basic'
import * as Slider_CenterOrigin from '@examples/slider/examples/center-origin'
import * as Slider_Context from '@examples/slider/examples/context'
import * as Slider_DraggingIndicator from '@examples/slider/examples/dragging-indicator'
import * as Slider_MinMax from '@examples/slider/examples/min-max'
import * as Slider_OnEvent from '@examples/slider/examples/on-event'
import * as Slider_Range from '@examples/slider/examples/range'
import * as Slider_RootProvider from '@examples/slider/examples/root-provider'
import * as Slider_Step from '@examples/slider/examples/step'
import * as Slider_ThumbAlignment from '@examples/slider/examples/thumb-alignment'
import * as Slider_ThumbOverlap from '@examples/slider/examples/thumb-overlap'
import * as Slider_Vertical from '@examples/slider/examples/vertical'
import * as Slider_WithMarks from '@examples/slider/examples/with-marks'
import * as Splitter_Basic from '@examples/splitter/examples/basic'
import * as Splitter_Collapsible from '@examples/splitter/examples/collapsible'
import * as Splitter_Context from '@examples/splitter/examples/context'
import * as Splitter_DynamicCollapsible from '@examples/splitter/examples/dynamic-collapsible'
import * as Splitter_MultiplePanels from '@examples/splitter/examples/multiple-panels'
import * as Splitter_ResizeIndicator from '@examples/splitter/examples/resize-indicator'
import * as Splitter_RootProvider from '@examples/splitter/examples/root-provider'
import * as Splitter_Vertical from '@examples/splitter/examples/vertical'
import * as Steps_Basic from '@examples/steps/examples/basic'
import * as Steps_Controlled from '@examples/steps/examples/controlled'
import * as Steps_RootProvider from '@examples/steps/examples/root-provider'
import * as Steps_Vertical from '@examples/steps/examples/vertical'
import * as Switch_Basic from '@examples/switch/examples/basic'
import * as Switch_Context from '@examples/switch/examples/context'
import * as Switch_Controlled from '@examples/switch/examples/controlled'
import * as Switch_Disabled from '@examples/switch/examples/disabled'
import * as Switch_InitialChecked from '@examples/switch/examples/initial-checked'
import * as Switch_RootProvider from '@examples/switch/examples/root-provider'
import * as Switch_WithField from '@examples/switch/examples/with-field'
import * as Tabs_Basic from '@examples/tabs/examples/basic'
import * as Tabs_Controlled from '@examples/tabs/examples/controlled'
import * as Tabs_DisabledTab from '@examples/tabs/examples/disabled-tab'
import * as Tabs_Indicator from '@examples/tabs/examples/indicator'
import * as Tabs_LazyMount from '@examples/tabs/examples/lazy-mount'
import * as Tabs_Links from '@examples/tabs/examples/links'
import * as Tabs_ManualActivation from '@examples/tabs/examples/manual-activation'
import * as Tabs_RootProvider from '@examples/tabs/examples/root-provider'
import * as Tabs_Vertical from '@examples/tabs/examples/vertical'
import * as TagsInput_Basic from '@examples/tags-input/examples/basic'
import * as TagsInput_BlurBehavior from '@examples/tags-input/examples/blur-behavior'
import * as TagsInput_ControlledInputValue from '@examples/tags-input/examples/controlled-input-value'
import * as TagsInput_Controlled from '@examples/tags-input/examples/controlled'
import * as TagsInput_Delimiter from '@examples/tags-input/examples/delimiter'
import * as TagsInput_DisabledEditing from '@examples/tags-input/examples/disabled-editing'
import * as TagsInput_Disabled from '@examples/tags-input/examples/disabled'
import * as TagsInput_Invalid from '@examples/tags-input/examples/invalid'
import * as TagsInput_MaxTagLength from '@examples/tags-input/examples/max-tag-length'
import * as TagsInput_MaxWithOverflow from '@examples/tags-input/examples/max-with-overflow'
import * as TagsInput_PasteBehavior from '@examples/tags-input/examples/paste-behavior'
import * as TagsInput_ProgrammaticControl from '@examples/tags-input/examples/programmatic-control'
import * as TagsInput_Readonly from '@examples/tags-input/examples/readonly'
import * as TagsInput_RootProvider from '@examples/tags-input/examples/root-provider'
import * as TagsInput_Validation from '@examples/tags-input/examples/validation'
import * as TagsInput_WithCombobox from '@examples/tags-input/examples/with-combobox'
import * as TagsInput_WithField from '@examples/tags-input/examples/with-field'
import * as Timer_Basic from '@examples/timer/examples/basic'
import * as Timer_Countdown from '@examples/timer/examples/countdown'
import * as Timer_Events from '@examples/timer/examples/events'
import * as Timer_Interval from '@examples/timer/examples/interval'
import * as Timer_Pomodoro from '@examples/timer/examples/pomodoro'
import * as Timer_RootProvider from '@examples/timer/examples/root-provider'
import * as Toast_Action from '@examples/toast/examples/action'
import * as Toast_Basic from '@examples/toast/examples/basic'
import * as Toast_Duration from '@examples/toast/examples/duration'
import * as Toast_MaxToasts from '@examples/toast/examples/max-toasts'
import * as Toast_Placement from '@examples/toast/examples/placement'
import * as Toast_PromiseToast from '@examples/toast/examples/promise-toast'
import * as Toast_Types from '@examples/toast/examples/types'
import * as Toast_Update from '@examples/toast/examples/update'
import * as Toast_VaryingHeight from '@examples/toast/examples/varying-height'
import * as ToggleGroup_Basic from '@examples/toggle-group/examples/basic'
import * as ToggleGroup_Controlled from '@examples/toggle-group/examples/controlled'
import * as ToggleGroup_Multiple from '@examples/toggle-group/examples/multiple'
import * as ToggleGroup_RootProvider from '@examples/toggle-group/examples/root-provider'
import * as Toggle_Basic from '@examples/toggle/examples/basic'
import * as Toggle_Context from '@examples/toggle/examples/context'
import * as Toggle_Controlled from '@examples/toggle/examples/controlled'
import * as Toggle_Disabled from '@examples/toggle/examples/disabled'
import * as Toggle_Indicator from '@examples/toggle/examples/indicator'
import * as Tooltip_Arrow from '@examples/tooltip/examples/arrow'
import * as Tooltip_Basic from '@examples/tooltip/examples/basic'
import * as Tooltip_Context from '@examples/tooltip/examples/context'
import * as Tooltip_Controlled from '@examples/tooltip/examples/controlled'
import * as Tooltip_Delay from '@examples/tooltip/examples/delay'
import * as Tooltip_Positioning from '@examples/tooltip/examples/positioning'
import * as Tooltip_RootProvider from '@examples/tooltip/examples/root-provider'
import * as Tooltip_WithinFixed from '@examples/tooltip/examples/within-fixed'
import * as Tour_AsyncStep from '@examples/tour/examples/async-step'
import * as Tour_Basic from '@examples/tour/examples/basic'
import * as Tour_Events from '@examples/tour/examples/events'
import * as Tour_KeyboardNavigation from '@examples/tour/examples/keyboard-navigation'
import * as Tour_MixedTypes from '@examples/tour/examples/mixed-types'
import * as Tour_ProgressBar from '@examples/tour/examples/progress-bar'
import * as Tour_SkipTour from '@examples/tour/examples/skip-tour'
import * as Tour_WaitForClick from '@examples/tour/examples/wait-for-click'
import * as Tour_WaitForElement from '@examples/tour/examples/wait-for-element'
import * as Tour_WaitForInput from '@examples/tour/examples/wait-for-input'
import * as TreeView_AsyncLoading from '@examples/tree-view/examples/async-loading'
import * as TreeView_Basic from '@examples/tree-view/examples/basic'
import * as TreeView_CheckboxTree from '@examples/tree-view/examples/checkbox-tree'
import * as TreeView_ContextMenu from '@examples/tree-view/examples/context-menu'
import * as TreeView_ControlledExpanded from '@examples/tree-view/examples/controlled-expanded'
import * as TreeView_ControlledSelected from '@examples/tree-view/examples/controlled-selected'
import * as TreeView_DisabledNode from '@examples/tree-view/examples/disabled-node'
import * as TreeView_ExpandCollapseAll from '@examples/tree-view/examples/expand-collapse-all'
import * as TreeView_Filtering from '@examples/tree-view/examples/filtering'
import * as TreeView_LazyMount from '@examples/tree-view/examples/lazy-mount'
import * as TreeView_Links from '@examples/tree-view/examples/links'
import * as TreeView_Mutation from '@examples/tree-view/examples/mutation'
import * as TreeView_RenameNode from '@examples/tree-view/examples/rename-node'
import * as TreeView_RootProvider from '@examples/tree-view/examples/root-provider'
import * as TreeView_Virtualized from '@examples/tree-view/examples/virtualized'
import * as Environment_Basic from '../../../packages/react/src/providers/environment/examples/basic'
import * as Environment_Setup from '../../../packages/react/src/providers/environment/examples/setup'
import * as Environment_ShadowRoot from '../../../packages/react/src/providers/environment/examples/shadow-root'
import * as Environment_Usage from '../../../packages/react/src/providers/environment/examples/usage'
import * as Locale_Basic from '../../../packages/react/src/providers/locale/examples/basic'
import * as Locale_Setup from '../../../packages/react/src/providers/locale/examples/setup'
import * as Locale_Usage from '../../../packages/react/src/providers/locale/examples/usage'

// Registry maps example keys to their module namespace
// Each module is imported as a namespace (import * as X) to handle varying export names
type ExampleModule = Record<string, unknown>

const exampleModules: Record<string, ExampleModule> = {
  'accordion/basic': Accordion_Basic,
  'accordion/collapsible': Accordion_Collapsible,
  'accordion/context': Accordion_Context,
  'accordion/controlled': Accordion_Controlled,
  'accordion/disabled': Accordion_Disabled,
  'accordion/horizontal': Accordion_Horizontal,
  'accordion/item-context': Accordion_ItemContext,
  'accordion/lazy-mount': Accordion_LazyMount,
  'accordion/multiple': Accordion_Multiple,
  'accordion/root-provider': Accordion_RootProvider,
  'accordion/with-slider': Accordion_WithSlider,
  'angle-slider/basic': AngleSlider_Basic,
  'angle-slider/context': AngleSlider_Context,
  'angle-slider/controlled': AngleSlider_Controlled,
  'angle-slider/disabled': AngleSlider_Disabled,
  'angle-slider/root-provider': AngleSlider_RootProvider,
  'angle-slider/step': AngleSlider_Step,
  'avatar/basic': Avatar_Basic,
  'avatar/context': Avatar_Context,
  'avatar/events': Avatar_Events,
  'avatar/provider': Avatar_Provider,
  'avatar/root-provider': Avatar_RootProvider,
  'bottom-sheet/basic': BottomSheet_Basic,
  'bottom-sheet/controlled': BottomSheet_Controlled,
  'bottom-sheet/modal': BottomSheet_Modal,
  'bottom-sheet/no-drag-area': BottomSheet_NoDragArea,
  'bottom-sheet/non-draggable': BottomSheet_NonDraggable,
  'bottom-sheet/root-provider': BottomSheet_RootProvider,
  'bottom-sheet/scrollable': BottomSheet_Scrollable,
  'bottom-sheet/snap-points': BottomSheet_SnapPoints,
  'carousel/autoplay': Carousel_Autoplay,
  'carousel/basic': Carousel_Basic,
  'carousel/controlled': Carousel_Controlled,
  'carousel/dynamic-slides': Carousel_DynamicSlides,
  'carousel/pause-on-hover': Carousel_PauseOnHover,
  'carousel/root-provider': Carousel_RootProvider,
  'carousel/scroll-to': Carousel_ScrollTo,
  'carousel/slides-per-page': Carousel_SlidesPerPage,
  'carousel/spacing': Carousel_Spacing,
  'carousel/thumbnail-indicator': Carousel_ThumbnailIndicator,
  'carousel/variable-size': Carousel_VariableSize,
  'carousel/vertical': Carousel_Vertical,
  'checkbox/basic': Checkbox_Basic,
  'checkbox/context': Checkbox_Context,
  'checkbox/controlled': Checkbox_Controlled,
  'checkbox/default-checked': Checkbox_DefaultChecked,
  'checkbox/disabled': Checkbox_Disabled,
  'checkbox/group-controlled': Checkbox_GroupControlled,
  'checkbox/group-provider': Checkbox_GroupProvider,
  'checkbox/group-with-fieldset': Checkbox_GroupWithFieldset,
  'checkbox/group-with-form': Checkbox_GroupWithForm,
  'checkbox/group-with-invalid': Checkbox_GroupWithInvalid,
  'checkbox/group-with-select-all': Checkbox_GroupWithSelectAll,
  'checkbox/group': Checkbox_Group,
  'checkbox/indeterminate': Checkbox_Indeterminate,
  'checkbox/root-provider': Checkbox_RootProvider,
  'checkbox/with-field': Checkbox_WithField,
  'checkbox/with-form': Checkbox_WithForm,
  'client-only/basic': ClientOnly_Basic,
  'client-only/with-fallback': ClientOnly_WithFallback,
  'clipboard/basic': Clipboard_Basic,
  'clipboard/context': Clipboard_Context,
  'clipboard/controlled': Clipboard_Controlled,
  'clipboard/copy-status': Clipboard_CopyStatus,
  'clipboard/root-provider': Clipboard_RootProvider,
  'clipboard/timeout': Clipboard_Timeout,
  'clipboard/value-text': Clipboard_ValueText,
  'collapsible/basic': Collapsible_Basic,
  'collapsible/disabled': Collapsible_Disabled,
  'collapsible/initial-open': Collapsible_InitialOpen,
  'collapsible/lazy-mount': Collapsible_LazyMount,
  'collapsible/nested': Collapsible_Nested,
  'collapsible/partial-collapse': Collapsible_PartialCollapse,
  'collapsible/root-provider': Collapsible_RootProvider,
  'collection/async-list/dependencies': CollectionAsyncList_Dependencies,
  'collection/async-list/filter': CollectionAsyncList_Filter,
  'collection/async-list/infinite-loading': CollectionAsyncList_InfiniteLoading,
  'collection/async-list/reload': CollectionAsyncList_Reload,
  'collection/async-list/sort-client-side': CollectionAsyncList_SortClientSide,
  'collection/async-list/sort-server-side': CollectionAsyncList_SortServerSide,
  'collection/list-selection/basic': CollectionListSelection_Basic,
  'collection/list-selection/multiple': CollectionListSelection_Multiple,
  'collection/list-selection/range': CollectionListSelection_Range,
  'color-picker/basic': ColorPicker_Basic,
  'color-picker/controlled': ColorPicker_Controlled,
  'color-picker/disabled': ColorPicker_Disabled,
  'color-picker/form-usage': ColorPicker_FormUsage,
  'color-picker/inline': ColorPicker_Inline,
  'color-picker/input-only': ColorPicker_InputOnly,
  'color-picker/open-controlled': ColorPicker_OpenControlled,
  'color-picker/root-provider': ColorPicker_RootProvider,
  'color-picker/slider-only': ColorPicker_SliderOnly,
  'color-picker/swatch-only': ColorPicker_SwatchOnly,
  'color-picker/swatches': ColorPicker_Swatches,
  'color-picker/value-swatch': ColorPicker_ValueSwatch,
  'color-picker/with-field': ColorPicker_WithField,
  'combobox/async-search': Combobox_AsyncSearch,
  'combobox/auto-highlight': Combobox_AutoHighlight,
  'combobox/basic': Combobox_Basic,
  'combobox/context': Combobox_Context,
  'combobox/creatable': Combobox_Creatable,
  'combobox/custom-object': Combobox_CustomObject,
  'combobox/dynamic': Combobox_Dynamic,
  'combobox/grouping': Combobox_Grouping,
  'combobox/highlight-matching-text': Combobox_HighlightMatchingText,
  'combobox/inline-autocomplete': Combobox_InlineAutocomplete,
  'combobox/limit-results': Combobox_LimitResults,
  'combobox/links': Combobox_Links,
  'combobox/multiple': Combobox_Multiple,
  'combobox/rehydrate-value': Combobox_RehydrateValue,
  'combobox/root-provider': Combobox_RootProvider,
  'combobox/virtualized': Combobox_Virtualized,
  'combobox/with-field': Combobox_WithField,
  'date-picker/basic': DatePicker_Basic,
  'date-picker/controlled': DatePicker_Controlled,
  'date-picker/default-value': DatePicker_DefaultValue,
  'date-picker/default-view': DatePicker_DefaultView,
  'date-picker/format-parse': DatePicker_FormatParse,
  'date-picker/inline': DatePicker_Inline,
  'date-picker/locale': DatePicker_Locale,
  'date-picker/min-max': DatePicker_MinMax,
  'date-picker/month-picker': DatePicker_MonthPicker,
  'date-picker/month-range': DatePicker_MonthRange,
  'date-picker/multi-selection': DatePicker_MultiSelection,
  'date-picker/multiple-months': DatePicker_MultipleMonths,
  'date-picker/presets': DatePicker_Presets,
  'date-picker/range-selection': DatePicker_RangeSelection,
  'date-picker/root-provider': DatePicker_RootProvider,
  'date-picker/unavailable': DatePicker_Unavailable,
  'date-picker/year-picker-range': DatePicker_YearPickerRange,
  'date-picker/year-picker': DatePicker_YearPicker,
  'dialog/alert-dialog': Dialog_AlertDialog,
  'dialog/basic': Dialog_Basic,
  'dialog/close-on-escape': Dialog_CloseOnEscape,
  'dialog/close-on-interact-outside': Dialog_CloseOnInteractOutside,
  'dialog/confirmation': Dialog_Confirmation,
  'dialog/context': Dialog_Context,
  'dialog/controlled': Dialog_Controlled,
  'dialog/final-focus': Dialog_FinalFocus,
  'dialog/initial-focus': Dialog_InitialFocus,
  'dialog/lazy-mount': Dialog_LazyMount,
  'dialog/nested': Dialog_Nested,
  'dialog/non-modal': Dialog_NonModal,
  'dialog/rapid-state-change': Dialog_RapidStateChange,
  'dialog/root-provider': Dialog_RootProvider,
  'download-trigger/basic': DownloadTrigger_Basic,
  'download-trigger/svg': DownloadTrigger_Svg,
  'download-trigger/with-promise': DownloadTrigger_WithPromise,
  'editable/basic': Editable_Basic,
  'editable/context': Editable_Context,
  'editable/controlled': Editable_Controlled,
  'editable/controls': Editable_Controls,
  'editable/double-click': Editable_DoubleClick,
  'editable/root-provider': Editable_RootProvider,
  'editable/textarea': Editable_Textarea,
  'editable/with-field': Editable_WithField,
  'field/custom-control': Field_CustomControl,
  'field/disabled': Field_Disabled,
  'field/input': Field_Input,
  'field/invalid': Field_Invalid,
  'field/required-indicator': Field_RequiredIndicator,
  'field/root-provider': Field_RootProvider,
  'field/select': Field_Select,
  'field/shadow-dom': Field_ShadowDom,
  'field/textarea-autoresize': Field_TextareaAutoresize,
  'field/textarea': Field_Textarea,
  'fieldset/basic': Fieldset_Basic,
  'fieldset/disabled': Fieldset_Disabled,
  'fieldset/invalid': Fieldset_Invalid,
  'fieldset/phone-input': Fieldset_PhoneInput,
  'fieldset/root-provider': Fieldset_RootProvider,
  'fieldset/with-checkbox': Fieldset_WithCheckbox,
  'fieldset/with-field': Fieldset_WithField,
  'file-upload/accepted-file-types': FileUpload_AcceptedFileTypes,
  'file-upload/basic': FileUpload_Basic,
  'file-upload/clear-trigger': FileUpload_ClearTrigger,
  'file-upload/directory-upload': FileUpload_DirectoryUpload,
  'file-upload/dropzone': FileUpload_Dropzone,
  'file-upload/error-handling': FileUpload_ErrorHandling,
  'file-upload/form-usage': FileUpload_FormUsage,
  'file-upload/initial-files': FileUpload_InitialFiles,
  'file-upload/media-capture': FileUpload_MediaCapture,
  'file-upload/pasting-files': FileUpload_PastingFiles,
  'file-upload/rejected-files': FileUpload_RejectedFiles,
  'file-upload/root-provider': FileUpload_RootProvider,
  'file-upload/transform-files': FileUpload_TransformFiles,
  'file-upload/with-field': FileUpload_WithField,
  'floating-panel/anchor-position': FloatingPanel_AnchorPosition,
  'floating-panel/basic': FloatingPanel_Basic,
  'floating-panel/context': FloatingPanel_Context,
  'floating-panel/controlled-open': FloatingPanel_ControlledOpen,
  'floating-panel/controlled-position': FloatingPanel_ControlledPosition,
  'floating-panel/controlled-size': FloatingPanel_ControlledSize,
  'floating-panel/lazy-mount': FloatingPanel_LazyMount,
  'focus-trap/autofocus': FocusTrap_Autofocus,
  'focus-trap/basic': FocusTrap_Basic,
  'focus-trap/initial-focus': FocusTrap_InitialFocus,
  'format/byte-basic': Format_ByteBasic,
  'format/byte-sizes': Format_ByteSizes,
  'format/byte-with-locale': Format_ByteWithLocale,
  'format/byte-with-unit-display': Format_ByteWithUnitDisplay,
  'format/byte-with-unit-system': Format_ByteWithUnitSystem,
  'format/byte-with-unit': Format_ByteWithUnit,
  'format/number-basic': Format_NumberBasic,
  'format/number-with-compact': Format_NumberWithCompact,
  'format/number-with-currency': Format_NumberWithCurrency,
  'format/number-with-locale': Format_NumberWithLocale,
  'format/number-with-percentage': Format_NumberWithPercentage,
  'format/number-with-unit': Format_NumberWithUnit,
  'format/relative-time-basic': Format_RelativeTimeBasic,
  'format/relative-time-short': Format_RelativeTimeShort,
  'frame/basic': Frame_Basic,
  'frame/inherit-styles': Frame_InheritStyles,
  'frame/script': Frame_Script,
  'frame/src-doc': Frame_SrcDoc,
  'highlight/basic': Highlight_Basic,
  'highlight/dynamic-query': Highlight_DynamicQuery,
  'highlight/exact-match': Highlight_ExactMatch,
  'highlight/ignore-case': Highlight_IgnoreCase,
  'highlight/match-all': Highlight_MatchAll,
  'highlight/multiple': Highlight_Multiple,
  'highlight/repeating-text': Highlight_RepeatingText,
  'hover-card/basic': HoverCard_Basic,
  'hover-card/context': HoverCard_Context,
  'hover-card/controlled': HoverCard_Controlled,
  'hover-card/delay': HoverCard_Delay,
  'hover-card/positioning': HoverCard_Positioning,
  'hover-card/root-provider': HoverCard_RootProvider,
  'image-cropper/aspect-ratio': ImageCropper_AspectRatio,
  'image-cropper/basic': ImageCropper_Basic,
  'image-cropper/circle': ImageCropper_Circle,
  'image-cropper/context': ImageCropper_Context,
  'image-cropper/controlled-zoom': ImageCropper_ControlledZoom,
  'image-cropper/crop-preview': ImageCropper_CropPreview,
  'image-cropper/events': ImageCropper_Events,
  'image-cropper/fixed': ImageCropper_Fixed,
  'image-cropper/flip': ImageCropper_Flip,
  'image-cropper/initial-crop': ImageCropper_InitialCrop,
  'image-cropper/min-max-size': ImageCropper_MinMaxSize,
  'image-cropper/reset': ImageCropper_Reset,
  'image-cropper/root-provider': ImageCropper_RootProvider,
  'image-cropper/rotation': ImageCropper_Rotation,
  'image-cropper/zoom-limits': ImageCropper_ZoomLimits,
  'json-tree-view/array-data': JsonTreeView_ArrayData,
  'json-tree-view/basic': JsonTreeView_Basic,
  'json-tree-view/errors': JsonTreeView_Errors,
  'json-tree-view/expand-level': JsonTreeView_ExpandLevel,
  'json-tree-view/functions': JsonTreeView_Functions,
  'json-tree-view/map-and-set': JsonTreeView_MapAndSet,
  'json-tree-view/regex': JsonTreeView_Regex,
  'json-tree-view/render-value': JsonTreeView_RenderValue,
  'json-tree-view/root-provider': JsonTreeView_RootProvider,
  'listbox/basic': Listbox_Basic,
  'listbox/controlled': Listbox_Controlled,
  'listbox/disabled-item': Listbox_DisabledItem,
  'listbox/extended-select': Listbox_ExtendedSelect,
  'listbox/filtering': Listbox_Filtering,
  'listbox/grid': Listbox_Grid,
  'listbox/group': Listbox_Group,
  'listbox/horizontal': Listbox_Horizontal,
  'listbox/multiple': Listbox_Multiple,
  'listbox/root-provider': Listbox_RootProvider,
  'listbox/select-all': Listbox_SelectAll,
  'listbox/value-text': Listbox_ValueText,
  'marquee/auto-fill': Marquee_AutoFill,
  'marquee/basic': Marquee_Basic,
  'marquee/finite-loops': Marquee_FiniteLoops,
  'marquee/pause-on-interaction': Marquee_PauseOnInteraction,
  'marquee/programmatic-control': Marquee_ProgrammaticControl,
  'marquee/reverse': Marquee_Reverse,
  'marquee/speed': Marquee_Speed,
  'marquee/vertical': Marquee_Vertical,
  'marquee/with-edges': Marquee_WithEdges,
  'menu/basic': Menu_Basic,
  'menu/checkbox-items': Menu_CheckboxItems,
  'menu/context-lazy-mount': Menu_ContextLazyMount,
  'menu/context': Menu_Context,
  'menu/controlled': Menu_Controlled,
  'menu/group': Menu_Group,
  'menu/item-context': Menu_ItemContext,
  'menu/links': Menu_Links,
  'menu/menu-in-dialog': Menu_MenuInDialog,
  'menu/menu-item-dialog': Menu_MenuItemDialog,
  'menu/multiple-menu': Menu_MultipleMenu,
  'menu/nested': Menu_Nested,
  'menu/radio-items': Menu_RadioItems,
  'menu/root-provider': Menu_RootProvider,
  'menu/select-event': Menu_SelectEvent,
  'navigation-menu/basic': NavigationMenu_Basic,
  'navigation-menu/context': NavigationMenu_Context,
  'navigation-menu/controlled': NavigationMenu_Controlled,
  'navigation-menu/root-provider': NavigationMenu_RootProvider,
  'navigation-menu/viewport': NavigationMenu_Viewport,
  'number-input/basic': NumberInput_Basic,
  'number-input/context': NumberInput_Context,
  'number-input/formatting': NumberInput_Formatting,
  'number-input/fraction-digits': NumberInput_FractionDigits,
  'number-input/min-max': NumberInput_MinMax,
  'number-input/mouse-wheel': NumberInput_MouseWheel,
  'number-input/root-provider': NumberInput_RootProvider,
  'number-input/scrubber': NumberInput_Scrubber,
  'number-input/with-field': NumberInput_WithField,
  'pagination/basic': Pagination_Basic,
  'pagination/context': Pagination_Context,
  'pagination/controlled': Pagination_Controlled,
  'pagination/customized': Pagination_Customized,
  'pagination/data-slicing': Pagination_DataSlicing,
  'pagination/link': Pagination_Link,
  'pagination/page-range': Pagination_PageRange,
  'pagination/page-size-control': Pagination_PageSizeControl,
  'pagination/root-provider': Pagination_RootProvider,
  'pagination/with-edges': Pagination_WithEdges,
  'password-input/autocomplete': PasswordInput_Autocomplete,
  'password-input/basic': PasswordInput_Basic,
  'password-input/controlled-visibility': PasswordInput_ControlledVisibility,
  'password-input/ignore-password-manager': PasswordInput_IgnorePasswordManager,
  'password-input/root-provider': PasswordInput_RootProvider,
  'password-input/strength-meter': PasswordInput_StrengthMeter,
  'password-input/with-field': PasswordInput_WithField,
  'password-input/with-validation': PasswordInput_WithValidation,
  'pin-input/basic': PinInput_Basic,
  'pin-input/blur-on-complete': PinInput_BlurOnComplete,
  'pin-input/custom-placeholder': PinInput_CustomPlaceholder,
  'pin-input/mask': PinInput_Mask,
  'pin-input/otp-mode': PinInput_OtpMode,
  'pin-input/root-provider': PinInput_RootProvider,
  'pin-input/with-field': PinInput_WithField,
  'popover/anchor': Popover_Anchor,
  'popover/arrow': Popover_Arrow,
  'popover/as-child': Popover_AsChild,
  'popover/basic': Popover_Basic,
  'popover/close-behavior': Popover_CloseBehavior,
  'popover/context': Popover_Context,
  'popover/controlled': Popover_Controlled,
  'popover/disable-outside-click': Popover_DisableOutsideClick,
  'popover/factory': Popover_Factory,
  'popover/initial-focus': Popover_InitialFocus,
  'popover/lazy-mount': Popover_LazyMount,
  'popover/modal': Popover_Modal,
  'popover/nested': Popover_Nested,
  'popover/positioning': Popover_Positioning,
  'popover/root-provider': Popover_RootProvider,
  'popover/same-width': Popover_SameWidth,
  'popover/with-dialog': Popover_WithDialog,
  'presence/basic': Presence_Basic,
  'presence/lazy-mount-and-unmount-on-exit': Presence_LazyMountAndUnmountOnExit,
  'presence/lazy-mount': Presence_LazyMount,
  'presence/skip-animation-on-mount': Presence_SkipAnimationOnMount,
  'presence/unmount-on-exit': Presence_UnmountOnExit,
  'progress/circular/basic': ProgressCircular_Basic,
  'progress/circular/controlled': ProgressCircular_Controlled,
  'progress/circular/indeterminate': ProgressCircular_Indeterminate,
  'progress/circular/initial-value': ProgressCircular_InitialValue,
  'progress/circular/min-max': ProgressCircular_MinMax,
  'progress/circular/root-provider': ProgressCircular_RootProvider,
  'progress/circular/with-label': ProgressCircular_WithLabel,
  'progress/linear/basic': ProgressLinear_Basic,
  'progress/linear/controlled': ProgressLinear_Controlled,
  'progress/linear/indeterminate': ProgressLinear_Indeterminate,
  'progress/linear/initial-value': ProgressLinear_InitialValue,
  'progress/linear/min-max': ProgressLinear_MinMax,
  'progress/linear/root-provider': ProgressLinear_RootProvider,
  'progress/linear/value-text': ProgressLinear_ValueText,
  'progress/linear/vertical': ProgressLinear_Vertical,
  'qr-code/basic': QrCode_Basic,
  'qr-code/controlled': QrCode_Controlled,
  'qr-code/download': QrCode_Download,
  'qr-code/error-correction': QrCode_ErrorCorrection,
  'qr-code/fill': QrCode_Fill,
  'qr-code/overlay': QrCode_Overlay,
  'qr-code/root-provider': QrCode_RootProvider,
  'radio-group/basic': RadioGroup_Basic,
  'radio-group/controlled': RadioGroup_Controlled,
  'radio-group/disabled': RadioGroup_Disabled,
  'radio-group/initial-value': RadioGroup_InitialValue,
  'radio-group/orientation': RadioGroup_Orientation,
  'radio-group/root-provider': RadioGroup_RootProvider,
  'radio-group/with-fieldset': RadioGroup_WithFieldset,
  'rating-group/basic': RatingGroup_Basic,
  'rating-group/controlled': RatingGroup_Controlled,
  'rating-group/disabled': RatingGroup_Disabled,
  'rating-group/form-usage': RatingGroup_FormUsage,
  'rating-group/half-star': RatingGroup_HalfStar,
  'rating-group/root-provider': RatingGroup_RootProvider,
  'rating-group/with-field': RatingGroup_WithField,
  'scroll-area/basic': ScrollArea_Basic,
  'scroll-area/both-directions': ScrollArea_BothDirections,
  'scroll-area/horizontal': ScrollArea_Horizontal,
  'scroll-area/nested': ScrollArea_Nested,
  'scroll-area/root-provider': ScrollArea_RootProvider,
  'segment-group/basic': SegmentGroup_Basic,
  'segment-group/conditional': SegmentGroup_Conditional,
  'segment-group/controlled': SegmentGroup_Controlled,
  'segment-group/disabled': SegmentGroup_Disabled,
  'segment-group/root-provider': SegmentGroup_RootProvider,
  'select/async': Select_Async,
  'select/basic': Select_Basic,
  'select/controlled': Select_Controlled,
  'select/dynamic-items': Select_DynamicItems,
  'select/form-library': Select_FormLibrary,
  'select/fully-controlled': Select_FullyControlled,
  'select/grouping': Select_Grouping,
  'select/lazy-mount': Select_LazyMount,
  'select/max-selected': Select_MaxSelected,
  'select/multiple': Select_Multiple,
  'select/overflow': Select_Overflow,
  'select/reactive-collection': Select_ReactiveCollection,
  'select/root-provider': Select_RootProvider,
  'select/select-all': Select_SelectAll,
  'select/select-on-highlight': Select_SelectOnHighlight,
  'select/with-field': Select_WithField,
  'signature-pad/basic': SignaturePad_Basic,
  'signature-pad/image-preview': SignaturePad_ImagePreview,
  'signature-pad/root-provider': SignaturePad_RootProvider,
  'signature-pad/with-field': SignaturePad_WithField,
  'slider/basic': Slider_Basic,
  'slider/center-origin': Slider_CenterOrigin,
  'slider/context': Slider_Context,
  'slider/dragging-indicator': Slider_DraggingIndicator,
  'slider/min-max': Slider_MinMax,
  'slider/on-event': Slider_OnEvent,
  'slider/range': Slider_Range,
  'slider/root-provider': Slider_RootProvider,
  'slider/step': Slider_Step,
  'slider/thumb-alignment': Slider_ThumbAlignment,
  'slider/thumb-overlap': Slider_ThumbOverlap,
  'slider/vertical': Slider_Vertical,
  'slider/with-marks': Slider_WithMarks,
  'splitter/basic': Splitter_Basic,
  'splitter/collapsible': Splitter_Collapsible,
  'splitter/context': Splitter_Context,
  'splitter/dynamic-collapsible': Splitter_DynamicCollapsible,
  'splitter/multiple-panels': Splitter_MultiplePanels,
  'splitter/resize-indicator': Splitter_ResizeIndicator,
  'splitter/root-provider': Splitter_RootProvider,
  'splitter/vertical': Splitter_Vertical,
  'steps/basic': Steps_Basic,
  'steps/controlled': Steps_Controlled,
  'steps/root-provider': Steps_RootProvider,
  'steps/vertical': Steps_Vertical,
  'switch/basic': Switch_Basic,
  'switch/context': Switch_Context,
  'switch/controlled': Switch_Controlled,
  'switch/disabled': Switch_Disabled,
  'switch/initial-checked': Switch_InitialChecked,
  'switch/root-provider': Switch_RootProvider,
  'switch/with-field': Switch_WithField,
  'tabs/basic': Tabs_Basic,
  'tabs/controlled': Tabs_Controlled,
  'tabs/disabled-tab': Tabs_DisabledTab,
  'tabs/indicator': Tabs_Indicator,
  'tabs/lazy-mount': Tabs_LazyMount,
  'tabs/links': Tabs_Links,
  'tabs/manual-activation': Tabs_ManualActivation,
  'tabs/root-provider': Tabs_RootProvider,
  'tabs/vertical': Tabs_Vertical,
  'tags-input/basic': TagsInput_Basic,
  'tags-input/blur-behavior': TagsInput_BlurBehavior,
  'tags-input/controlled-input-value': TagsInput_ControlledInputValue,
  'tags-input/controlled': TagsInput_Controlled,
  'tags-input/delimiter': TagsInput_Delimiter,
  'tags-input/disabled-editing': TagsInput_DisabledEditing,
  'tags-input/disabled': TagsInput_Disabled,
  'tags-input/invalid': TagsInput_Invalid,
  'tags-input/max-tag-length': TagsInput_MaxTagLength,
  'tags-input/max-with-overflow': TagsInput_MaxWithOverflow,
  'tags-input/paste-behavior': TagsInput_PasteBehavior,
  'tags-input/programmatic-control': TagsInput_ProgrammaticControl,
  'tags-input/readonly': TagsInput_Readonly,
  'tags-input/root-provider': TagsInput_RootProvider,
  'tags-input/validation': TagsInput_Validation,
  'tags-input/with-combobox': TagsInput_WithCombobox,
  'tags-input/with-field': TagsInput_WithField,
  'timer/basic': Timer_Basic,
  'timer/countdown': Timer_Countdown,
  'timer/events': Timer_Events,
  'timer/interval': Timer_Interval,
  'timer/pomodoro': Timer_Pomodoro,
  'timer/root-provider': Timer_RootProvider,
  'toast/action': Toast_Action,
  'toast/basic': Toast_Basic,
  'toast/duration': Toast_Duration,
  'toast/max-toasts': Toast_MaxToasts,
  'toast/placement': Toast_Placement,
  'toast/promise-toast': Toast_PromiseToast,
  'toast/types': Toast_Types,
  'toast/update': Toast_Update,
  'toast/varying-height': Toast_VaryingHeight,
  'toggle-group/basic': ToggleGroup_Basic,
  'toggle-group/controlled': ToggleGroup_Controlled,
  'toggle-group/multiple': ToggleGroup_Multiple,
  'toggle-group/root-provider': ToggleGroup_RootProvider,
  'toggle/basic': Toggle_Basic,
  'toggle/context': Toggle_Context,
  'toggle/controlled': Toggle_Controlled,
  'toggle/disabled': Toggle_Disabled,
  'toggle/indicator': Toggle_Indicator,
  'tooltip/arrow': Tooltip_Arrow,
  'tooltip/basic': Tooltip_Basic,
  'tooltip/context': Tooltip_Context,
  'tooltip/controlled': Tooltip_Controlled,
  'tooltip/delay': Tooltip_Delay,
  'tooltip/positioning': Tooltip_Positioning,
  'tooltip/root-provider': Tooltip_RootProvider,
  'tooltip/within-fixed': Tooltip_WithinFixed,
  'tour/async-step': Tour_AsyncStep,
  'tour/basic': Tour_Basic,
  'tour/events': Tour_Events,
  'tour/keyboard-navigation': Tour_KeyboardNavigation,
  'tour/mixed-types': Tour_MixedTypes,
  'tour/progress-bar': Tour_ProgressBar,
  'tour/skip-tour': Tour_SkipTour,
  'tour/wait-for-click': Tour_WaitForClick,
  'tour/wait-for-element': Tour_WaitForElement,
  'tour/wait-for-input': Tour_WaitForInput,
  'tree-view/async-loading': TreeView_AsyncLoading,
  'tree-view/basic': TreeView_Basic,
  'tree-view/checkbox-tree': TreeView_CheckboxTree,
  'tree-view/context-menu': TreeView_ContextMenu,
  'tree-view/controlled-expanded': TreeView_ControlledExpanded,
  'tree-view/controlled-selected': TreeView_ControlledSelected,
  'tree-view/disabled-node': TreeView_DisabledNode,
  'tree-view/expand-collapse-all': TreeView_ExpandCollapseAll,
  'tree-view/filtering': TreeView_Filtering,
  'tree-view/lazy-mount': TreeView_LazyMount,
  'tree-view/links': TreeView_Links,
  'tree-view/mutation': TreeView_Mutation,
  'tree-view/rename-node': TreeView_RenameNode,
  'tree-view/root-provider': TreeView_RootProvider,
  'tree-view/virtualized': TreeView_Virtualized,
  'environment/basic': Environment_Basic,
  'environment/setup': Environment_Setup,
  'environment/shadow-root': Environment_ShadowRoot,
  'environment/usage': Environment_Usage,
  'locale/basic': Locale_Basic,
  'locale/setup': Locale_Setup,
  'locale/usage': Locale_Usage,
}

/**
 * Get the first component export from a module
 */
function getComponentFromModule(mod: ExampleModule): ComponentType | undefined {
  // Find the first function/component export (skip type exports)
  for (const key of Object.keys(mod)) {
    const value = mod[key]
    if (typeof value === 'function') {
      return value as ComponentType
    }
  }
  return undefined
}

/**
 * Get an example component by component name and example id
 */
export function getExample(component: string, example: string): ComponentType | undefined {
  const mod = exampleModules[`${component}/${example}`]
  if (!mod) return undefined
  return getComponentFromModule(mod)
}

/**
 * Check if an example exists
 */
export function hasExample(component: string, example: string): boolean {
  return `${component}/${example}` in exampleModules
}
