export type { StatusChangeDetails as AvatarStatusChangeDetails } from '@zag-js/avatar'
export { AvatarContext, type AvatarContextProps } from './avatar-context'
export { AvatarFallback, type AvatarFallbackProps } from './avatar-fallback'
export { AvatarImage, type AvatarImageProps } from './avatar-image'
export { AvatarRoot, type AvatarRootProps } from './avatar-root'
export { AvatarRootProvider, type AvatarRootProviderProps } from './avatar-root-provider'
export { useAvatar, type UseAvatarProps, type UseAvatarReturn } from './use-avatar'
export { useAvatarContext, type UseAvatarContext } from './use-avatar-context'

export * as Avatar from './avatar'
