/// <reference types="vitest" />
import angular from '@analogjs/vite-plugin-angular'
import { defineConfig } from 'vitest/config'

export default defineConfig(({ mode }) => ({
  plugins: [angular()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['src/setup-test.ts'],
    include: ['**/*.spec.ts', '**/*.spec.mts'],
    coverage: {
      provider: 'v8',
    },
  },
  resolve: {
    alias: {
      '@ark-ui/angular/accordion': new URL('./src/accordion/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/angle-slider': new URL('./angle-slider/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/avatar': new URL('./avatar/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/carousel': new URL('./src/carousel/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/clipboard': new URL('./clipboard/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/checkbox': new URL('./checkbox/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/collapsible': new URL('./src/collapsible/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/color-picker': new URL('./src/color-picker/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/combobox': new URL('./combobox/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/date-input': new URL('./src/date-input/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/date-picker': new URL('./src/date-picker/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/dialog': new URL('./src/dialog/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/drawer': new URL('./src/drawer/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/editable': new URL('./editable/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/field': new URL('./field/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/fieldset': new URL('./fieldset/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/file-upload': new URL('./file-upload/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/floating-panel': new URL('./src/floating-panel/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/hover-card': new URL('./src/hover-card/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/image-cropper': new URL('./src/image-cropper/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/json-tree-view': new URL('./src/json-tree-view/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/listbox': new URL('./listbox/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/marquee': new URL('./src/marquee/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/menu': new URL('./src/menu/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/navigation-menu': new URL('./src/navigation-menu/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/number-input': new URL('./number-input/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/pagination': new URL('./src/pagination/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/password-input': new URL('./password-input/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/pin-input': new URL('./pin-input/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/popover': new URL('./src/popover/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/portal': new URL('./src/portal/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/presence': new URL('./src/presence/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/progress': new URL('./progress/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/qr-code': new URL('./src/qr-code/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/radio-group': new URL('./radio-group/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/rating-group': new URL('./rating-group/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/scroll-area': new URL('./src/scroll-area/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/segment-group': new URL('./segment-group/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/select': new URL('./select/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/signature-pad': new URL('./src/signature-pad/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/splitter': new URL('./src/splitter/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/steps': new URL('./src/steps/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/slider': new URL('./slider/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/switch': new URL('./switch/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/tabs': new URL('./src/tabs/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/tags-input': new URL('./tags-input/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/timer': new URL('./src/timer/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/toast': new URL('./src/toast/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/toggle': new URL('./toggle/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/toggle-group': new URL('./toggle-group/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/tooltip': new URL('./src/tooltip/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/tour': new URL('./src/tour/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/tree-view': new URL('./src/tree-view/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/src/collection': new URL('./src/collection/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/src/_zag': new URL('./src/_zag/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/src/internal': new URL('./src/internal/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/src/presence': new URL('./src/presence/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/src/providers/environment': new URL('./src/providers/environment/public-api.ts', import.meta.url)
        .pathname,
      '@ark-ui/angular/src/providers/locale': new URL('./src/providers/locale/public-api.ts', import.meta.url).pathname,
      '@ark-ui/angular/src/tree-view': new URL('./src/tree-view/public-api.ts', import.meta.url).pathname,
    },
    conditions: ['source', 'module', 'browser', 'import', 'default'],
  },
  define: {
    'import.meta.vitest': mode !== 'production',
  },
}))
