import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'
import { Outfit } from 'next/font/google'
import Script from 'next/script'
import type { PropsWithChildren } from 'react'
import './global.css'

const outfit = Outfit({ subsets: ['latin'], variable: '--font-outfit' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en" className={outfit.variable} suppressHydrationWarning>
      <head>
        <Script src="https://plausible.io/js/plausible.js" data-domain="ark-ui.com" />
      </head>
      <body>
        <ThemeProvider attribute="class">{props.children}</ThemeProvider>
      </body>
    </html>
  )
}
