export { TabContent, type TabContentProps } from './tab-content'
export { TabIndicator, type TabIndicatorProps } from './tab-indicator'
export { TabList, type TabListProps } from './tab-list'
export { TabTrigger, type TabTriggerProps } from './tab-trigger'
export { Tabs, type TabsProps } from './tabs'
export { tabsAnatomy } from './tabs.anatomy'
