export type { SizeChangeDetails as SplitterSizeChangeDetails } from '@zag-js/splitter'
export * as Splitter from './splitter'
export { SplitterContext, type SplitterContextProps } from './splitter-context'
export { SplitterPanel, type SplitterPanelProps } from './splitter-panel'
export { SplitterResizeTrigger, type SplitterResizeTriggerProps } from './splitter-resize-trigger'
export { SplitterRoot, type SplitterRootProps } from './splitter-root'
export { useSplitterContext, type UseSplitterContext } from './use-splitter-context'
