name: Main Workflow
on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=2 origin +refs/heads/main:refs/remotes/origin/main
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install
        uses: pnpm/action-setup@v2
        with:
          version: '7'
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
