name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install
        uses: pnpm/action-setup@v2
        with:
          version: '7'
          run_install: true

      - name: Build
        # Website is already built on Vercel
        run: pnpm build --filter=\!@ark-ui/website

      - name: Tests
        run: pnpm test

      - name: ESLint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Prettier
        run: pnpm format:check

      - name: Run exports:check
        run: pnpm exports:check
