name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: bun run build

  # docs:
  #   name: Docs
  #   # This workflow doesn't work on forks
  #   if: github.repository == 'chakra-ui/ark'
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: write

  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v4

  #     - name: Install
  #       uses: ./.github/composite-actions/install

  #     - name: Generate TypeDocs
  #       run: bun scripts document:types

  #     - uses: stefanzweifel/git-auto-commit-action@v5
  #       with:
  #         commit_message: 'docs: update types and storydocs'

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests
        run: bun run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run lint
        run: bun run lint

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run typecheck
        run: bun run typecheck

  checks:
    name: Check for various issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Check component exports
        run: bun scripts check:exports

      - name: Check for same HTML tags
        run: bun scripts check:nodes
