name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v7

      - name: Install
        uses: ./.github/composite-actions/install

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Build packages
        run: bun run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v2.1.1
        with:
          version-script: bun run version
          publish-script: bun run release
          pr-title: 'chore: release packages'
          commit-message: 'chore: release packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
