name: Publish

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SAGE_PAT }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: bun run build

      - name: Publish packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          commit: 'ci(changesets): version packages'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
